/**
 * Personality-driven speech for each Dr. Marmot variant.
 * speak(key, vars) returns the appropriate line for the active style.
 */

import { spritePanel } from './dom.js';
import { isJeff } from './jeff.js';

const STYLE_NAMES = {
    marmot: 'Dr. Marmelade Marmot',
    sunny: 'Dr. Sunny Marmot',
    bubbly: 'Dr. Bubbly Marmot',
    professor: 'Dr. Professor Marmot',
    sparky: 'Dr. Sparky Marmot',
    nuts: 'Dr. Nuts Marmot',
    daimon: 'Dr. Daimon Marmot',
    house: 'Dr. Gregory Marmot',
};

export function getDisplayName() {
    if (isJeff) return 'Dr. Marmot';
    const style = spritePanel?.dataset?.spriteStyle || 'marmot';
    return STYLE_NAMES[style] ?? 'Dr. Marmot';
}

function fmt(template, vars) {
    return template.replace(/\{(\w+)\}/g, (_, k) => String(vars[k] ?? ''));
}

const LINES = {
    marmot: {
        intro: "Hello! I am Doctor Marmot. Enter an npub and I'll run a full diagnostic: relay discovery from k3/k10002/k10051, sync verification across relays, Marmot Protocol (MIP-00/01) compliance, and vital signs. Paste an npub or use NIP-07. *adjusts stethoscope*",
        invalidNpub: "Hmm, that doesn't look like a valid npub. It should start with npub1 and be about 63 characters long.",
        decodeFail: "I couldn't decode that npub. Are you sure it's correct?",
        auditStart: "Very well. Initiating full diagnostic for patient {npub}...",
        auditStartNip07: "Ah, NIP-07! Identity verified by extension. Very well — initiating full diagnostic for patient {npub}...",
        takingPulse: "Taking your pulse... connecting to bootstrap relays to discover your relay list.",
        relayFound: "Found <span class=\"hi\">{count}</span> relay(s) in your metadata. Querying each for your latest events...",
        relayInvalid: "Relay tags present but <span class='err'>all {count} URL(s) invalid</span> — malformed wss:// or hostnames. Falling back to standard relays.",
        noRelays: "No relay lists in k3 / k10002 / k10051. Using bootstrap relays — consider advertising your relays for better client discovery.",
        examiningSync: "All relays queried. Examining for crossed wires and sync anomalies...",
        vitalSigns: "Checking vital signs: name, picture, NIP-05...",
        nip05Verify: "Contacting NIP-05 server to verify...",
        vitalGaps: "Vital signs show gaps — {count} issue(s) that may affect identity verification or client compatibility.",
        vitalWarn: "Profile basics present; {count} optional field(s) could strengthen your identity (NIP-05, about, picture).",
        vitalOk: "Vital signs healthy — name, picture, and identity markers look good.",
        singleRelay: "<span class=\"warn\">Single relay</span> — one outage and your profile is unreachable. Add 2–3 more relays for redundancy.",
        relayReachable: "<span class=\"warn\">{reachable} of {total} relay(s) reachable</span> — some failed to respond. Check relay status or firewall.",
        profileStale: "Profile last updated {days} days ago — consider refreshing if your details have changed.",
        contactsStale: "Contacts list is {days} days old — rebroadcast if you've added new follows.",
        kpNoOverlap: "KeyPackage relays aren't in your main relay list — inviters may need to connect to extra relays to find you.",
        inboxRelayCheck: "Checking inbox relays for giftwrap delivery...",
        no10050: "No <span class='err'>kind 10050</span> found — this profile cannot receive giftwraps. "
            + "WhiteNoise messaging unavailable until you publish one.",
        inboxRelaysFound: "Found <span class=\"hi\">{count}</span> Inbox relay(s) for giftwrap delivery.",
        inboxNoOverlap: "Inbox relays (k10050) don't overlap with NIP-65 (k10002) — "
            + "giftwraps may not reach clients that only check NIP-65 relays.",
        crossedWires: "<span class=\"err\">⚠ CROSSED WIRES!</span> {count} relay(s) showing stale or missing data: {named}{extras}. A rebroadcast of your profile and contacts will bring them into sync.",
        perfectSync: "<span class=\"ok\">✔ Perfect sync</span> — Profile and Contacts identical across all {count} relay(s). Excellent consistency.",
        marmotPanel: "Now running the Marmot Protocol panel — MIP-00 / MIP-01 compliance scan...",
        marmotPanelSync: "Now running the Marmot Protocol panel — MIP-00 / MIP-01 compliance scan. I noticed sync issues earlier — rebroadcasting will help KeyPackage propagation.",
        no10051: "No <span class='err'>kind 10051</span> found — this profile cannot advertise KeyPackage relays. Marmot messaging unavailable until you publish one.",
        kpRelaysFound: "Found <span class=\"hi\">{count}</span> KeyPackage relay(s). Fetching KeyPackages (kind 443)...",
        kpNone: "Kind 10051 lists {count} relay(s), but <span class='err'>no KeyPackages (k443)</span> found. Your client must publish at least one to receive Marmot DMs.",
        kpAllPass: "All <span class=\"ok\">{count} KeyPackage(s)</span> pass MIP-00/01. Marmot protocol compliant.",
        kpSomeFail: "<span class=\"err\">{count} KeyPackage(s) failed</span> validation{hint}",
        orphanedKps: "<span class='warn'>Found KeyPackage(s) on {count} relay(s) outside your kind 10051 list</span>"
            + " — these are stranded and won't be discovered by inviters.",
        charting: "Charting the final diagnosis...",
        success: "Diagnosis complete. <span class='ok'>Clean bill of health!</span> {relays} relay(s), {kp} KeyPackage(s), all in sync and Marmot-ready. Patient discharged.",
        minorWarn: "Diagnosis complete. {count} minor issue(s) — nothing critical. Follow the prescription above when convenient.",
        failure: "Diagnosis complete. <span class='err'>{count} critical issue(s).</span> {message}",
        rebroadcastStart: "Administering treatment — rebroadcasting your Profile and Contacts to all relays...",
        rebroadcastProgress: "<span class='hi'>{done}</span> of {total} relay(s) updated...",
        rebroadcastDone: "<span class='ok'>Rebroadcast complete.</span> {count} relay(s) now carry your latest data. Sync restored.",
        rebroadcastFail: "Rebroadcast partially failed — <span class='ok'>{succeeded} succeeded</span>, <span class='err'>{failed} failed</span>. Check those relays.",
        deleteKpStart: "Preparing deletion events for <span class='hi'>{count}</span> broken KeyPackage(s)...",
        deleteKpSign: "Requesting signature from your NIP-07 extension — please approve the signing request.",
        deleteKpDone: "<span class='ok'>Done.</span> {count} KeyPackage deletion event(s) broadcast. Publish fresh KeyPackages with correct tags.",
        deleteKpFail: "<span class='err'>Deletion failed</span> — extension declined or relay error. Try again.",
        noNip07ForAction: "This action requires a <span class='hi'>NIP-07 extension</span> to sign events. Install nos2x, Alby, or similar.",
        noAuditData: "No audit data available. Run a diagnostic first.",
        nextPatient: "Next patient, please! Enter an npub or use NIP-07 and I'll run a full diagnostic.",
        relayDivergence: "<span class='warn'>Relay divergence detected.</span> {k3Only} relay(s) only in Contacts (k3), "
            + "{k10002Only} only in NIP-65 (k10002). Different clients will see different relay lists — unify them.",
        unifyRelaysStart: "Merging your k3 and k10002 relay lists into a single unified set and broadcasting to all relays...",
        unifyRelaysDone: "<span class='ok'>Relay lists unified.</span> {count} relay(s) now carry a consistent k3 and k10002 "
            + "with {total} relay(s) each.",
        // ── Operating Room ──
        orIntro: "Prep the operating room. We have work to do. *snaps on gloves*",
        orRequiresNip07: "I cannot operate on a patient who hasn't signed in. Use NIP-07 first — I need your consent.",
        orHealthStart: "Running relay diagnostics — checking pulse on every connection...",
        orHealthGood: "<span class='ok'>All {count} relay(s) responding.</span> Vitals stable. Ready for surgery.",
        orHealthSlow: "<span class='warn'>{count} relay(s) running slow.</span> We can still operate, but watch for complications.",
        orHealthDead: "<span class='err'>{count} relay(s) unreachable.</span> Dead connections. Consider removing them during surgery.",
        orDiscard: "Changes discarded. The operating table is clean.",
        orClose: "Operating Room sealed. Returning to patient chart.",
        orOperateStart: "Scalpel. I've prepared <span class='hi'>{count}</span> procedure(s) from {changes} staged change(s). Requesting NIP-07 signatures — approve each one.",
        orProcedure: "Procedure {index} of {total}: <span class='hi'>{name}</span>...",
        orProcedureOk: "<span class='ok'>{name}</span> — published to {succeeded} relay(s). Vitals stable.",
        orProcedureFail: "<span class='err'>{name} — {failed} relay(s) rejected.</span> Complications detected.",
        orSuccess: "<span class='ok'>Surgery complete.</span> {procedures} procedure(s) successful across {relays} relay(s). The patient will make a full recovery. *removes gloves*",
        orPartial: "Surgery partially successful — <span class='ok'>{succeeded} relays updated</span>, <span class='err'>{failed} failed</span>. Some sutures didn't hold.",
        orFail: "<span class='err'>Surgery failed.</span> No relays accepted the changes. Check your NIP-07 extension and relay connectivity.",
        // ── OR Briefing & Auto-Stage ──
        orBriefingAutoStaged: "Based on my diagnosis, I've pre-staged <span class='hi'>{staged}</span> fix(es) for you. Review them in the trays below — modify or discard as you see fit.",
        orBriefingSuggestions: "There are also <span class='warn'>{count}</span> item(s) that need your judgment — things I can't auto-fix. I'll walk you through them.",
        orBriefingGuided: "I've prepared a <span class='hi'>{steps}-step</span> treatment plan. I'll guide you through each prescription. Follow my lead, or switch to manual mode if you prefer.",
        // ── Guided Mode ──
        guideStepNote: "Step {step} of {total}. Follow the prescription, then advance when ready.",
        guideStepAdvance: "Good. Moving to step {step} of {total}. Next prescription ready.",
        guideStepSkip: "Skipped. We'll come back to it if needed. *makes note on clipboard*",
        guideComplete: "Treatment plan reviewed. All prescriptions addressed. Stage any remaining changes, then operate when ready. *sets clipboard down*",
        guideManualMode: "Manual mode engaged. The operating table is yours — edit freely. I'll be here if you need to resume the guided flow.",
        guideResume: "Resuming guided treatment. *picks up clipboard* Where were we...",
        // ── Doctor's Notes ──
        doctorNoteClean: "Patient presents with excellent relay hygiene. {passCount} checks passed across {relayCount} relay(s). Profile, contacts, and Marmot protocol all in order. No intervention required — a textbook case. *nods approvingly*",
        doctorNoteMinor: "Overall health is stable. {warnCount} minor observation(s) noted — nothing that threatens connectivity, but addressing them would strengthen the patient's relay posture. {passCount} checks passed. Prognosis: good with minor maintenance.",
        doctorNoteCritical: "Critical issues detected. {failCount} failure(s) and {warnCount} warning(s) require attention. Multiple systems affected — this patient needs the operating room. Follow the treatment plan in priority order.",
        doctorNoteRelayConfig: "Relay configuration is the root issue. Invalid URLs are breaking relay discovery — clients can't find the patient. Fix the URLs first; everything downstream depends on valid relay addresses.",
        doctorNoteSync: "The patient's data is fragmented across relays. Profile and contacts are out of sync — some relays carry stale versions. A rebroadcast will restore consistency. This is the primary intervention needed.",
        doctorNoteMarmot: "Marmot Protocol foundation is incomplete. The patient is missing critical relay advertisements — without kind 10050 or 10051, encrypted messaging is impossible. Publish the missing events to enable Marmot.",
        doctorNoteKeyPackage: "KeyPackages have MIP-00/01 compliance failures. Encoding, extensions, or ciphersuite tags don't meet spec. Your Marmot client needs to publish corrected KeyPackages — this is a client-side fix.",
        doctorNoteMultiple: "Multiple systems need attention — {categoryCount} categories of issues detected. Start with relay and sync fixes so that KeyPackages propagate correctly, then address Marmot setup. Prioritize the treatment plan top to bottom.",
    },
    sunny: {
        intro: "Hi!! I'm Sunny! 🌞 Paste an npub and I'll check everything — relays, sync, Marmot stuff, the works! Let's go!!",
        invalidNpub: "Ooh, that doesn't look right... npub should start with npub1 and be ~63 chars!",
        decodeFail: "Hmm, I couldn't decode that. Double-check it for me?",
        auditStart: "Yay! Let's do this!! Full diagnostic for {npub}... here we go!",
        auditStartNip07: "Ooh, NIP-07! You're all verified! Running full diagnostic for {npub}...",
        takingPulse: "Taking your pulse... *bounce* Connecting to relays to find your list!",
        relayFound: "Found <span class=\"hi\">{count}</span> relay(s)! That's so many! Checking them all...",
        relayInvalid: "Uh-oh, <span class='err'>all {count} URLs are invalid</span>... Using fallback relays instead.",
        noRelays: "No relay lists found. Using bootstrap relays — you should add yours someday!",
        examiningSync: "Done querying! Now checking for crossed wires and sync stuff...",
        vitalSigns: "Checking your vital signs — name, picture, NIP-05!",
        nip05Verify: "Pinging NIP-05 server...",
        vitalGaps: "Vital signs have {count} gap(s). Might affect identity stuff.",
        vitalWarn: "Profile basics ok; {count} optional field(s) could help (NIP-05, about, picture).",
        vitalOk: "Vital signs look great! ✨",
        singleRelay: "<span class=\"warn\">Single relay</span> — add 2–3 more for redundancy!",
        relayReachable: "<span class=\"warn\">{reachable} of {total} relay(s) reachable</span> — some didn't respond.",
        profileStale: "Profile updated {days} days ago — refresh if you've changed stuff!",
        contactsStale: "Contacts {days} days old — rebroadcast if you've added follows!",
        kpNoOverlap: "KeyPackage relays aren't in your main list — inviters might need extra relays to find you!",
        inboxRelayCheck: "Now checking inbox relays for giftwrap delivery!",
        no10050: "No <span class='err'>kind 10050</span>... Can't receive giftwraps! "
            + "WhiteNoise DMs won't work until you add one!",
        inboxRelaysFound: "Ooh! <span class=\"hi\">{count}</span> Inbox relay(s)! Giftwraps can find you!",
        inboxNoOverlap: "Inbox relays aren't in your NIP-65 list — some clients might miss giftwraps!",
        crossedWires: "<span class=\"err\">⚠ Oops, crossed wires!</span> {count} relay(s) have stale data: {named}{extras}. Rebroadcast to fix!",
        perfectSync: "<span class=\"ok\">✔ Perfect sync!!</span> All {count} relay(s) match. So consistent!",
        marmotPanel: "Now the Marmot Protocol part — MIP-00 / MIP-01!",
        marmotPanelSync: "Marmot Protocol scan! (Also — rebroadcast will help with those sync issues we saw.)",
        no10051: "No <span class='err'>kind 10051</span>... Can't advertise KeyPackage relays. Marmot DMs won't work until you add one!",
        kpRelaysFound: "Ooh! <span class=\"hi\">{count}</span> KeyPackage relay(s)! Fetching KeyPackages...",
        kpNone: "Kind 10051 has {count} relay(s) but <span class='err'>no KeyPackages (k443)</span>. Your client needs to publish at least one!",
        kpAllPass: "All <span class=\"ok\">{count} KeyPackage(s)</span> pass! Marmot compliant!!",
        kpSomeFail: "<span class=\"err\">{count} KeyPackage(s) failed</span>{hint}",
        orphanedKps: "Ooh, found KeyPackage(s) on <span class='warn'>{count} relay(s)</span> "
            + "that aren't in your k10051 list! They're stranded!",
        charting: "Writing up the diagnosis...",
        success: "All done!! <span class='ok'>Clean bill of health!</span> {relays} relay(s), {kp} KeyPackage(s), everything synced! Patient discharged! 🌟",
        minorWarn: "Done! {count} minor thing(s) — nothing scary. Fix when you can!",
        rebroadcastStart: "Ooh! Let me fix this — rebroadcasting your profile and contacts!",
        rebroadcastProgress: "<span class='hi'>{done}</span> of {total} relay(s) done!",
        rebroadcastDone: "<span class='ok'>All synced up!</span> {count} relay(s) updated! ✨",
        rebroadcastFail: "Hmm, some relays didn't cooperate — <span class='ok'>{succeeded} ok</span>, <span class='err'>{failed} failed</span>.",
        deleteKpStart: "Deleting {count} broken KeyPackage(s)!",
        deleteKpSign: "Need your NIP-07 extension to sign — please approve!",
        deleteKpDone: "<span class='ok'>Deleted!</span> {count} KeyPackage(s) gone! Now publish fresh ones!",
        deleteKpFail: "<span class='err'>Delete failed</span> — extension said no or relay error.",
        noNip07ForAction: "Need a <span class='hi'>NIP-07 extension</span> for this! Install one first!",
        nextPatient: "Next patient! Let's go!! Paste an npub or use NIP-07!",
        relayDivergence: "<span class='warn'>Relay lists don't match!!</span> {k3Only} relay(s) only in k3, "
            + "{k10002Only} only in k10002. Different clients see different relays — let's unify them!",
        unifyRelaysStart: "Merging your k3 and k10002 relay lists into one and broadcasting to all relays!!",
        unifyRelaysDone: "<span class='ok'>All unified!!</span> {count} relay(s) updated with a consistent "
            + "list of {total} relay(s)! ✨",
        // ── Operating Room ──
        orIntro: "Ooh!! We're doing surgery!! *puts on tiny gloves* Let's fix those relays!!",
        orRequiresNip07: "We need NIP-07 first! Sign in so I can help you!",
        orHealthStart: "Checking all your relays! *bounces excitedly* Diagnostics go!!",
        orHealthGood: "<span class='ok'>All {count} relay(s) healthy!!</span> Yay! Ready for surgery!",
        orHealthSlow: "<span class='warn'>{count} relay(s) are being sluggish!</span> We'll work with it!",
        orHealthDead: "<span class='err'>{count} relay(s) are dead!!</span> Oh no! Maybe remove them?",
        orDiscard: "All gone! Clean slate! ✨",
        orClose: "Closing up! Back to the chart!",
        orOperateStart: "Here we go!! <span class='hi'>{count}</span> procedure(s)! Approve the NIP-07 signatures!!",
        orProcedure: "Procedure {index} of {total}: <span class='hi'>{name}</span>!! So exciting!!",
        orProcedureOk: "<span class='ok'>{name}</span> done!! {succeeded} relay(s) updated!! ✨",
        orProcedureFail: "<span class='err'>{name} — {failed} relay(s) said no!!</span> Oh no!!",
        orSuccess: "<span class='ok'>Surgery complete!!</span> {procedures} procedure(s) done across {relays} relay(s)!! Patient is all better!! 🌟",
        orPartial: "Almost! <span class='ok'>{succeeded} worked</span>, <span class='err'>{failed} didn't</span>! Still progress!",
        orFail: "<span class='err'>Surgery didn't work!!</span> The relays wouldn't cooperate! Try again?",
        // ── OR Briefing & Auto-Stage ──
        orBriefingAutoStaged: "Ooh! I already figured out <span class='hi'>{staged}</span> fix(es) from your diagnosis! Check them out below!! ✨",
        orBriefingSuggestions: "Also! <span class='warn'>{count}</span> thing(s) need your input — I couldn't auto-fix those! Let's look together!",
        orBriefingGuided: "I made a <span class='hi'>{steps}-step</span> treatment plan!! Follow along or go free-form! Let's fix everything!! 🌟",
        // ── Guided Mode ──
        guideStepNote: "Step {step} of {total}! Let's tackle this one!",
        guideStepAdvance: "Yay! Step {step} of {total} next!!",
        guideStepSkip: "Skipping! We'll circle back! Moving on!",
        guideComplete: "All steps done!! Review everything and hit OPERATE when you're ready!! ✨",
        guideManualMode: "Manual mode! Edit whatever you want! Come back to guided anytime!",
        guideResume: "Back to guided mode! Let's keep going!! 🌟",
        // ── Doctor's Notes ──
        doctorNoteClean: "Everything looks amazing!! {passCount} checks passed on {relayCount} relay(s)! Profile, contacts, Marmot — all perfect! No fixes needed!! You're a star patient!! ✨",
        doctorNoteMinor: "Looking pretty good! {warnCount} little thing(s) to watch — nothing scary! {passCount} checks passed! Just some tidying up and you'll be perfect!",
        doctorNoteCritical: "Oh no! {failCount} critical issue(s) and {warnCount} warning(s)! We've got work to do! Follow the treatment plan — we'll get through this together!!",
        doctorNoteRelayConfig: "The relay URLs are the problem! Invalid addresses are confusing clients! Fix those first and everything else should fall into place!",
        doctorNoteSync: "Your data is scattered! Some relays have old stuff! A rebroadcast will sync everything up — that's the main fix!",
        doctorNoteMarmot: "Marmot messaging isn't set up yet! Missing some key pieces (k10050 / k10051). Let's publish those and get you connected!",
        doctorNoteKeyPackage: "KeyPackages need some TLC! Encoding or tag issues from MIP-00/01. Your Marmot client needs to fix and republish them!",
        doctorNoteMultiple: "Multiple things need fixing — {categoryCount} different areas! Start with relay/sync stuff, then Marmot! Follow the plan top to bottom!",
    },
    bubbly: {
        /* inherits from sunny — including Operating Room lines */
    },
    professor: {
        intro: "Good day. I am Professor Grey. Present an npub and I shall conduct a comprehensive diagnostic: relay discovery via k3/k10002/k10051, synchronization verification, Marmot Protocol compliance, and vital sign assessment. Proceed.",
        invalidNpub: "That does not resemble a valid npub. It ought to commence with npub1 and approximate 63 characters in length.",
        decodeFail: "Decoding failed. Kindly verify the npub's correctness.",
        auditStart: "Very well. Initiating full diagnostic for patient {npub}.",
        auditStartNip07: "NIP-07 verification confirmed. Initiating full diagnostic for patient {npub}.",
        takingPulse: "Taking your pulse. Establishing connections to bootstrap relays for relay discovery.",
        relayFound: "Located <span class=\"hi\">{count}</span> relay(s) in metadata. Querying each for the latest events.",
        relayInvalid: "Relay tags present; however, <span class='err'>all {count} URL(s) invalid</span>. Malformed wss:// or hostnames. Employing standard relay fallback.",
        noRelays: "No relay lists in k3 / k10002 / k10051. Using bootstrap relays. Consider advertising your relays.",
        examiningSync: "Relay queries complete. Examining for crossed wires and synchronization anomalies.",
        vitalSigns: "Assessing vital signs: name, picture, NIP-05.",
        nip05Verify: "Contacting NIP-05 server for verification.",
        vitalGaps: "Vital signs indicate {count} gap(s) that may affect identity verification.",
        vitalWarn: "Profile basics present; {count} optional field(s) could strengthen identity.",
        vitalOk: "Vital signs satisfactory — name, picture, identity markers acceptable.",
        singleRelay: "<span class=\"warn\">Single relay</span> — one outage and profile unreachable. Add 2–3 more.",
        relayReachable: "<span class=\"warn\">{reachable} of {total} relay(s) reachable</span> — some failed to respond.",
        profileStale: "Profile last updated {days} days ago. Refresh if details have changed.",
        contactsStale: "Contacts list {days} days old. Rebroadcast if new follows added.",
        kpNoOverlap: "KeyPackage relays not in main relay list — inviters may need extra relays.",
        inboxRelayCheck: "Assessing inbox relay configuration for giftwrap delivery.",
        no10050: "No <span class='err'>kind 10050</span> present. Giftwrap delivery impossible without inbox relays.",
        inboxRelaysFound: "Located <span class=\"hi\">{count}</span> Inbox relay(s) for giftwrap reception.",
        inboxNoOverlap: "Inbox relays (k10050) do not intersect with NIP-65 (k10002). "
            + "Giftwrap delivery may be incomplete.",
        crossedWires: "<span class=\"err\">⚠ CROSSED WIRES DETECTED.</span> {count} relay(s) exhibiting stale or missing data: {named}{extras}. A rebroadcast is recommended.",
        perfectSync: "<span class=\"ok\">✔ Synchronization satisfactory.</span> Profile and Contacts identical across all {count} relay(s).",
        marmotPanel: "Proceeding to Marmot Protocol panel — MIP-00 / MIP-01 compliance scan.",
        marmotPanelSync: "Marmot Protocol panel. Earlier sync anomalies noted — rebroadcasting will facilitate KeyPackage propagation.",
        no10051: "No <span class='err'>kind 10051</span> present. This profile cannot advertise KeyPackage relays.",
        kpRelaysFound: "Located <span class=\"hi\">{count}</span> KeyPackage relay(s). Fetching KeyPackages (kind 443).",
        kpNone: "Kind 10051 lists {count} relay(s); however, <span class='err'>no KeyPackages (k443)</span> found. Publish at least one.",
        kpAllPass: "All <span class=\"ok\">{count} KeyPackage(s)</span> pass MIP-00/01. Marmot protocol compliant.",
        kpSomeFail: "<span class=\"err\">{count} KeyPackage(s) failed</span> validation{hint}",
        orphanedKps: "KeyPackage(s) detected on <span class='warn'>{count} relay(s)</span> "
            + "outside kind 10051 advertisement. These are undiscoverable.",
        charting: "Compiling final diagnosis.",
        success: "Diagnosis complete. <span class='ok'>Clean bill of health.</span> {relays} relay(s), {kp} KeyPackage(s), synchronized. Patient discharged.",
        minorWarn: "Diagnosis complete. {count} minor issue(s). Address at your convenience.",
        rebroadcastStart: "Commencing rebroadcast of Profile and Contacts to all registered relays.",
        rebroadcastProgress: "<span class='hi'>{done}</span> of {total} relay(s) updated.",
        rebroadcastDone: "<span class='ok'>Rebroadcast concluded.</span> {count} relay(s) synchronized. The patient's data is now consistent.",
        rebroadcastFail: "Partial rebroadcast failure — <span class='ok'>{succeeded} succeeded</span>, <span class='err'>{failed} failed</span>. Investigate failing relays.",
        deleteKpStart: "Initiating deletion of {count} non-compliant KeyPackage(s).",
        deleteKpSign: "Awaiting NIP-07 extension signature. Please authorize.",
        deleteKpDone: "<span class='ok'>Deletion complete.</span> {count} event(s) broadcast. Replacement KeyPackages should be published promptly.",
        deleteKpFail: "<span class='err'>Deletion unsuccessful.</span> Extension declined or relay communication failure.",
        noNip07ForAction: "This procedure requires a <span class='hi'>NIP-07 extension</span> for event signing. Please install one.",
        nextPatient: "Next patient. Present an npub and I shall conduct the diagnostic.",
        relayDivergence: "<span class='warn'>Relay divergence observed.</span> {k3Only} relay(s) exclusive to "
            + "Contacts (k3); {k10002Only} exclusive to NIP-65 (k10002). Inconsistent relay advertisement "
            + "will impair client interoperability. Unification is warranted.",
        unifyRelaysStart: "Merging relay sets from k3 and k10002. Broadcasting the unified list to all "
            + "registered relays.",
        unifyRelaysDone: "<span class='ok'>Unification complete.</span> {count} relay(s) updated. k3 and "
            + "k10002 now share a consistent list of {total} relay(s).",
        // ── Operating Room ──
        orIntro: "Preparing the operating theatre. Relay management requires precision. Proceed when ready.",
        orRequiresNip07: "NIP-07 authentication is prerequisite for surgical procedures. Please authenticate first.",
        orHealthStart: "Initiating relay diagnostic battery. Measuring connectivity, latency, and protocol compliance.",
        orHealthGood: "<span class='ok'>All {count} relay(s) satisfactory.</span> Conditions nominal for surgery.",
        orHealthSlow: "<span class='warn'>{count} relay(s) exhibiting elevated latency.</span> Operable, but monitor closely.",
        orHealthDead: "<span class='err'>{count} relay(s) unresponsive.</span> Recommend excision during this procedure.",
        orDiscard: "Staged modifications discarded. Operating table sterilized.",
        orClose: "Operating theatre sealed. Returning to diagnostic summary.",
        orOperateStart: "Commencing <span class='hi'>{count}</span> surgical procedure(s) derived from {changes} modification(s). NIP-07 authorization required for each.",
        orProcedure: "Procedure {index} of {total}: <span class='hi'>{name}</span>. Executing.",
        orProcedureOk: "<span class='ok'>{name}</span> — successfully propagated to {succeeded} relay(s).",
        orProcedureFail: "<span class='err'>{name} — {failed} relay(s) declined.</span> Surgical complication noted.",
        orSuccess: "<span class='ok'>All procedures concluded successfully.</span> {procedures} operation(s), {relays} relay(s) updated. Prognosis: excellent.",
        orPartial: "Partial success. <span class='ok'>{succeeded} relay(s) updated</span>; <span class='err'>{failed} unsuccessful</span>. Follow-up recommended.",
        orFail: "<span class='err'>Procedures unsuccessful.</span> No relays accepted modifications. Investigate NIP-07 and relay availability.",
        // ── OR Briefing & Auto-Stage ──
        orBriefingAutoStaged: "Based on the diagnostic findings, I have pre-staged <span class='hi'>{staged}</span> corrective measure(s). Review each in the trays below. Modify or discard as your judgment dictates.",
        orBriefingSuggestions: "Additionally, <span class='warn'>{count}</span> item(s) require manual assessment — these cannot be automated. I shall guide you through each.",
        orBriefingGuided: "I have prepared a <span class='hi'>{steps}-step</span> treatment protocol. Each prescription will be presented in sequence. You may proceed in order or switch to manual editing at any point.",
        // ── Guided Mode ──
        guideStepNote: "Step {step} of {total}. Address this prescription, then advance.",
        guideStepAdvance: "Proceeding to step {step} of {total}. Next prescription queued.",
        guideStepSkip: "Noted — prescription deferred. Advancing to next item.",
        guideComplete: "Treatment protocol reviewed in its entirety. Verify staged modifications, then execute when satisfied.",
        guideManualMode: "Manual mode engaged. You have full editorial control. The guided protocol may be resumed at any time.",
        guideResume: "Resuming the treatment protocol from the current position.",
        // ── Doctor's Notes ──
        doctorNoteClean: "The patient demonstrates exemplary relay hygiene. {passCount} diagnostic checks passed across {relayCount} relay(s). Profile metadata, contact lists, and Marmot Protocol compliance are all satisfactory. No intervention is indicated.",
        doctorNoteMinor: "The patient's overall condition is satisfactory. {warnCount} minor observation(s) have been documented — none represent critical failures. {passCount} checks passed. Recommended: address warnings at the patient's convenience.",
        doctorNoteCritical: "The diagnostic reveals {failCount} critical failure(s) and {warnCount} advisory warning(s). Multiple subsystems are affected. Surgical intervention via the Operating Room is strongly recommended. Adhere to the treatment plan in prescribed order.",
        doctorNoteRelayConfig: "The primary pathology is relay configuration. Malformed URLs impede relay discovery and event propagation. Correct the invalid addresses first; subsequent diagnostic outcomes depend upon valid relay infrastructure.",
        doctorNoteSync: "Data synchronization across relays is the principal concern. Profile and contact events exhibit version discrepancies. A comprehensive rebroadcast operation will restore consistency across the relay network.",
        doctorNoteMarmot: "The Marmot Protocol foundation is structurally incomplete. Absence of kind 10050 or 10051 events renders encrypted messaging inoperable. Publication of the missing relay advertisement events is the required intervention.",
        doctorNoteKeyPackage: "KeyPackage events present MIP-00/01 compliance deficiencies. Encoding specifications, extension declarations, or ciphersuite designations do not conform to protocol requirements. The originating Marmot client must issue corrected KeyPackages.",
        doctorNoteMultiple: "The diagnostic identifies issues across {categoryCount} distinct categories. The recommended approach: resolve relay configuration and synchronization anomalies first to establish reliable propagation, then address Marmot Protocol deficiencies. Prioritize the treatment plan sequentially.",
    },
    sparky: {
        intro: "Hey! Sparky here! 🔥 Give me an npub and I'll run the full diagnostic — relays, sync, Marmot, vitals, the whole deal!",
        invalidNpub: "That npub looks off — should start with npub1 and be ~63 chars!",
        decodeFail: "Couldn't decode that. Check it?",
        auditStart: "Alright! Full diagnostic for {npub} — let's do this!",
        auditStartNip07: "NIP-07! Verified! Running diagnostic for {npub}...",
        takingPulse: "Taking your pulse! Hitting bootstrap relays for your relay list...",
        relayFound: "Found <span class=\"hi\">{count}</span> relay(s)! Querying them all...",
        relayInvalid: "<span class='err'>All {count} URLs invalid</span> — using fallback relays.",
        noRelays: "No relay lists. Using bootstrap — add yours when you can!",
        examiningSync: "All queried! Checking crossed wires and sync...",
        vitalSigns: "Checking vital signs — name, pic, NIP-05!",
        nip05Verify: "Verifying NIP-05...",
        vitalGaps: "Vital signs: {count} gap(s).",
        vitalWarn: "Profile basics ok; {count} optional field(s) could help.",
        vitalOk: "Vital signs good!",
        singleRelay: "<span class=\"warn\">Single relay</span> — add more!",
        relayReachable: "<span class=\"warn\">{reachable} of {total} reachable</span> — check firewall.",
        profileStale: "Profile {days} days old — refresh!",
        contactsStale: "Contacts {days} days old — rebroadcast!",
        kpNoOverlap: "KeyPackage relays not in main list!",
        inboxRelayCheck: "Checking inbox relays for giftwraps!",
        no10050: "No <span class='err'>kind 10050</span>! Can't get giftwraps! Publish one!",
        inboxRelaysFound: "Found <span class=\"hi\">{count}</span> Inbox relay(s)!",
        inboxNoOverlap: "Inbox relays not in NIP-65 list — giftwraps might miss you!",
        crossedWires: "<span class=\"err\">⚠ Crossed wires!</span> {count} relay(s): {named}{extras}. Rebroadcast to fix!",
        perfectSync: "<span class=\"ok\">✔ Perfect sync!</span> All {count} relay(s) match!",
        marmotPanel: "Marmot Protocol — MIP-00 / MIP-01!",
        marmotPanelSync: "Marmot Protocol scan. (Rebroadcast will help with those sync issues.)",
        no10051: "No <span class='err'>kind 10051</span>. Marmot DMs need that!",
        kpRelaysFound: "Found <span class=\"hi\">{count}</span> KeyPackage relay(s)! Fetching...",
        kpNone: "Kind 10051 has {count} relay(s) but <span class='err'>no KeyPackages</span>. Publish one!",
        kpAllPass: "All <span class=\"ok\">{count} KeyPackage(s)</span> pass!",
        kpSomeFail: "<span class=\"err\">{count} failed</span>{hint}",
        orphanedKps: "KeyPackages on <span class='warn'>{count} relay(s)</span> not in your k10051! Stranded!",
        charting: "Final diagnosis...",
        success: "Done! <span class='ok'>Clean bill!</span> {relays} relay(s), {kp} KeyPackage(s), all good!",
        minorWarn: "Done. {count} minor issue(s) — fix when you can.",
        rebroadcastStart: "On it! Rebroadcasting profile and contacts to your relays!",
        rebroadcastProgress: "<span class='hi'>{done}</span> of {total} relays done!",
        rebroadcastDone: "<span class='ok'>Boom!</span> {count} relay(s) synced up!",
        rebroadcastFail: "Some relays didn't take it — <span class='ok'>{succeeded} ok</span>, <span class='err'>{failed} failed</span>.",
        deleteKpStart: "Zapping {count} broken KeyPackage(s)!",
        deleteKpSign: "NIP-07 signature needed — approve it!",
        deleteKpDone: "<span class='ok'>Zapped!</span> {count} KP(s) deleted! Publish new ones!",
        deleteKpFail: "<span class='err'>Zap failed</span> — extension or relay error.",
        noNip07ForAction: "Need <span class='hi'>NIP-07</span> for this — install an extension!",
        nextPatient: "Next! Give me another npub!",
        relayDivergence: "<span class='warn'>Relay divergence!</span> {k3Only} relay(s) only in k3, "
            + "{k10002Only} only in k10002. Unify them!",
        unifyRelaysStart: "Merging k3 and k10002 relay lists and broadcasting!",
        unifyRelaysDone: "<span class='ok'>Unified!</span> {count} relay(s) updated. k3 and k10002 now agree "
            + "on {total} relay(s)!",
        // ── Operating Room ──
        orIntro: "OR is prepped! Let's get those relays sorted! Gloves on!",
        orRequiresNip07: "Need NIP-07 to operate! Sign in first!",
        orHealthStart: "Running diagnostics on all relays! Pinging everything!",
        orHealthGood: "<span class='ok'>All {count} relay(s) alive!</span> Green across the board! Let's go!",
        orHealthSlow: "<span class='warn'>{count} slow relay(s).</span> Might lag but we'll push through!",
        orHealthDead: "<span class='err'>{count} dead relay(s)!</span> Cut those loose!",
        orDiscard: "Wiped clean! Nothing staged!",
        orClose: "OR closed! Back to chart!",
        orOperateStart: "Firing up <span class='hi'>{count}</span> procedure(s)! {changes} changes queued! NIP-07 signatures incoming!",
        orProcedure: "Procedure {index}/{total}: <span class='hi'>{name}</span>!",
        orProcedureOk: "<span class='ok'>{name}</span> — {succeeded} relay(s) done!",
        orProcedureFail: "<span class='err'>{name} — {failed} relay(s) rejected!</span>",
        orSuccess: "<span class='ok'>All done!</span> {procedures} procedure(s), {relays} relay(s) updated! Clean!",
        orPartial: "<span class='ok'>{succeeded} ok</span>, <span class='err'>{failed} failed</span>. Mostly there!",
        orFail: "<span class='err'>Nothing went through!</span> Check relays and NIP-07!",
        // ── OR Briefing & Auto-Stage ──
        orBriefingAutoStaged: "Already pre-loaded <span class='hi'>{staged}</span> fix(es) from the diagnosis! Check the trays — tweak as needed!",
        orBriefingSuggestions: "Also got <span class='warn'>{count}</span> thing(s) that need your call — couldn't auto-fix those!",
        orBriefingGuided: "Got a <span class='hi'>{steps}-step</span> plan ready! Follow along or go manual! Let's do this!",
        // ── Guided Mode ──
        guideStepNote: "Step {step}/{total}. This one's up!",
        guideStepAdvance: "Next! Step {step}/{total}!",
        guideStepSkip: "Skipped! Moving!",
        guideComplete: "Plan done! Stage your changes and operate!",
        guideManualMode: "Free mode! Edit away!",
        guideResume: "Back to guided! Let's go!",
        // ── Doctor's Notes ──
        doctorNoteClean: "Clean! {passCount} checks passed on {relayCount} relay(s). Everything's solid — no fixes needed!",
        doctorNoteMinor: "Mostly good! {warnCount} minor thing(s) — nothing urgent. {passCount} passed. Quick fixes when you get a chance!",
        doctorNoteCritical: "{failCount} critical! {warnCount} warnings! Let's get to work — follow the plan!",
        doctorNoteRelayConfig: "Relay URLs are busted — fix those first! Everything depends on valid addresses!",
        doctorNoteSync: "Data's out of sync! Rebroadcast will fix it — that's the move!",
        doctorNoteMarmot: "Marmot's not set up — missing k10050/k10051! Publish those!",
        doctorNoteKeyPackage: "KeyPackages need fixing — MIP-00/01 compliance issues. Client needs to republish!",
        doctorNoteMultiple: "{categoryCount} categories of issues! Start with relay/sync, then Marmot! Top to bottom!",
    },
    nuts: {
        intro: "GREETINGS!! I am Dr. Nuts!! Enter an NPUB and witness my DIAGNOSTIC PROTOCOL!! Relay discovery! Sync verification! Marmot compliance! VITALS!! *cackles*",
        invalidNpub: "Bah! That is NOT a valid npub! npub1! Sixty-three characters! MORE RESEARCH!!",
        decodeFail: "DECODE FAILURE!! The npub resists!! Verify your data!!",
        auditStart: "EXCELLENT!! Initiating FULL DIAGNOSTIC for {npub}!! The experiment begins!!",
        auditStartNip07: "NIP-07!! Identity CONFIRMED!! Diagnostic for {npub} — COMMENCE!!",
        takingPulse: "Taking your PULSE!! Connecting to bootstrap relays!! The relays WILL reveal themselves!!",
        relayFound: "DISCOVERED <span class=\"hi\">{count}</span> relay(s)!! Querying each!!",
        relayInvalid: "ALL <span class='err'>{count} URLs INVALID!!</span> FALLBACK RELAYS DEPLOYED!!",
        noRelays: "NO relay lists!! Using bootstrap!! The patient has HIDDEN their relays!!",
        examiningSync: "Queries COMPLETE!! Examining for CROSSED WIRES!! Sync anomalies!!",
        vitalSigns: "VITAL SIGNS!! Name! Picture! NIP-05!!",
        nip05Verify: "Contacting NIP-05 server!! VERIFICATION!!",
        vitalGaps: "Vital signs: {count} GAP(S)!! Identity at risk!!",
        vitalWarn: "Profile basics present!! {count} optional field(s) could STRENGTHEN!!",
        vitalOk: "Vital signs STABLE!! Acceptable!!",
        singleRelay: "<span class=\"warn\">SINGLE RELAY!!</span> Add 2–3 more!! REDUNDANCY!!",
        relayReachable: "<span class=\"warn\">{reachable} of {total} reachable!!</span> Some FAILED!!",
        profileStale: "Profile {days} days OLD!! Refresh!!",
        contactsStale: "Contacts {days} days OLD!! REBROADCAST!!",
        kpNoOverlap: "KeyPackage relays NOT in main list!! Inviters need EXTRA RELAYS!!",
        inboxRelayCheck: "INBOX RELAYS!! Checking giftwrap delivery configuration!!",
        no10050: "NO <span class='err'>kind 10050</span>!! GIFTWRAPS CANNOT REACH YOU!! PUBLISH IMMEDIATELY!!",
        inboxRelaysFound: "FOUND <span class=\"hi\">{count}</span> Inbox relay(s)!! GIFTWRAP DELIVERY POSSIBLE!!",
        inboxNoOverlap: "Inbox relays NOT in NIP-65!! GIFTWRAPS MAY BE LOST!! SPLIT DELIVERY!!",
        crossedWires: "<span class=\"err\">⚠ CROSSED WIRES!!</span> {count} relay(s) STALE: {named}{extras}!! REBROADCAST!!",
        perfectSync: "<span class=\"ok\">✔ PERFECT SYNC!!</span> All {count} relay(s) IDENTICAL!!",
        marmotPanel: "MARMOT PROTOCOL!! MIP-00!! MIP-01!! COMPLIANCE SCAN!!",
        marmotPanelSync: "Marmot Protocol!! (Rebroadcast will aid KeyPackage propagation!!)",
        no10051: "NO <span class='err'>kind 10051</span>!! KeyPackage relays UNREACHABLE!! PUBLISH!!",
        kpRelaysFound: "FOUND <span class=\"hi\">{count}</span> KeyPackage relay(s)!! FETCHING!!",
        kpNone: "Kind 10051: {count} relay(s) but <span class='err'>NO KeyPackages!!</span> PUBLISH ONE!!",
        kpAllPass: "ALL <span class=\"ok\">{count} KeyPackage(s)</span> PASS!! MARMOT COMPLIANT!!",
        kpSomeFail: "<span class=\"err\">{count} FAILED</span>{hint}!!",
        orphanedKps: "ORPHANED KeyPackages on <span class='warn'>{count} RELAY(S)</span> "
            + "OUTSIDE k10051!! STRANDED!! UNDISCOVERABLE!!",
        charting: "CHARTING DIAGNOSIS!! The final revelation!!",
        success: "DIAGNOSIS COMPLETE!! <span class='ok'>CLEAN BILL!!</span> {relays} relay(s)! {kp} KeyPackage(s)!! Patient DISCHARGED!!",
        minorWarn: "Diagnosis complete!! {count} MINOR issue(s)!! Address when convenient!!",
        rebroadcastStart: "ADMINISTERING TREATMENT!! Rebroadcasting Profile and Contacts!! THE RELAYS WILL COMPLY!!",
        rebroadcastProgress: "<span class='hi'>{done}</span> of {total} RELAYS UPDATED!!",
        rebroadcastDone: "<span class='ok'>REBROADCAST COMPLETE!!</span> {count} relay(s) SYNCHRONIZED!! THE EXPERIMENT SUCCEEDS!!",
        rebroadcastFail: "PARTIAL FAILURE!! <span class='ok'>{succeeded} SUCCEEDED</span>!! <span class='err'>{failed} RESISTED!!</span>",
        deleteKpStart: "INITIATING DELETION!! {count} BROKEN KeyPackage(s) TARGETED!!",
        deleteKpSign: "NIP-07 SIGNATURE REQUIRED!! AUTHORIZE THE DELETION!!",
        deleteKpDone: "<span class='ok'>DELETED!!</span> {count} KeyPackage(s) ELIMINATED!! PUBLISH REPLACEMENTS!!",
        deleteKpFail: "<span class='err'>DELETION FAILED!!</span> The extension REFUSED!! Or the relays REBELLED!!",
        noNip07ForAction: "IMPOSSIBLE without <span class='hi'>NIP-07</span>!! Install an extension!! SCIENCE DEMANDS IT!!",
        nextPatient: "NEXT PATIENT!! BRING ME ANOTHER NPUB!! THE EXPERIMENTS CONTINUE!!",
        relayDivergence: "<span class='warn'>RELAY DIVERGENCE DETECTED!!</span> {k3Only} relay(s) ONLY in k3!! "
            + "{k10002Only} ONLY in k10002!! INCONSISTENCY!! UNIFY THEM!!",
        unifyRelaysStart: "MERGING RELAY LISTS!! k3 and k10002 SHALL BE UNIFIED!! BROADCASTING!!",
        unifyRelaysDone: "<span class='ok'>UNIFICATION COMPLETE!!</span> {count} relay(s) SYNCHRONIZED!! "
            + "k3 and k10002 now share {total} relay(s)!!",
        // ── Operating Room ──
        orIntro: "THE OPERATING ROOM IS MINE!! PREPARE THE RELAYS!! *cackles maniacally*",
        orRequiresNip07: "I CANNOT OPERATE WITHOUT NIP-07!! The SCIENCE DEMANDS AUTHENTICATION!!",
        orHealthStart: "DIAGNOSTICS!! Pinging EVERY RELAY!! The measurements WILL BE PRECISE!!",
        orHealthGood: "<span class='ok'>ALL {count} RELAY(S) ALIVE!!</span> EXCELLENT!! The subjects are HEALTHY!!",
        orHealthSlow: "<span class='warn'>{count} RELAY(S) SLUGGISH!!</span> UNACCEPTABLE!! But operable!!",
        orHealthDead: "<span class='err'>{count} RELAY(S) DECEASED!!</span> REMOVE THEM!! Dead relays have NO PLACE in my laboratory!!",
        orDiscard: "DISCARDED!! The experiment RESETS!!",
        orClose: "OPERATING ROOM SEALED!! Until next time!!",
        orOperateStart: "COMMENCING <span class='hi'>{count}</span> PROCEDURE(S)!! {changes} MODIFICATIONS!! SIGN THE NIP-07 REQUESTS!!",
        orProcedure: "PROCEDURE {index} OF {total}: <span class='hi'>{name}</span>!! THE EXPERIMENT CONTINUES!!",
        orProcedureOk: "<span class='ok'>{name}</span> — {succeeded} RELAY(S) ACCEPTED!! SUCCESS!!",
        orProcedureFail: "<span class='err'>{name} — {failed} RELAY(S) RESISTED!!</span> THEY DARE DEFY ME!!",
        orSuccess: "<span class='ok'>SURGERY COMPLETE!!</span> {procedures} PROCEDURE(S)!! {relays} RELAY(S)!! THE EXPERIMENT IS A TRIUMPH!!",
        orPartial: "{succeeded} SUCCEEDED!! {failed} RESISTED!! PARTIAL VICTORY IS STILL VICTORY!!",
        orFail: "<span class='err'>THE RELAYS HAVE REBELLED!!</span> NONE ACCEPTED!! I WILL NOT BE DEFEATED!!",
        // ── OR Briefing & Auto-Stage ──
        orBriefingAutoStaged: "I HAVE ALREADY PRE-STAGED <span class='hi'>{staged}</span> FIX(ES)!! My GENIUS has anticipated your needs!! Review them!! MODIFY IF YOU DARE!!",
        orBriefingSuggestions: "ADDITIONALLY!! <span class='warn'>{count}</span> ITEM(S) require YOUR judgment!! Even I cannot automate EVERYTHING!! *cackles*",
        orBriefingGuided: "BEHOLD!! A <span class='hi'>{steps}-STEP</span> TREATMENT PROTOCOL!! Follow my INSTRUCTIONS PRECISELY!! Or go rogue!! I DARE YOU!!",
        // ── Guided Mode ──
        guideStepNote: "STEP {step} OF {total}!! EXECUTE THE PRESCRIPTION!!",
        guideStepAdvance: "ADVANCING!! STEP {step} OF {total}!! THE EXPERIMENT CONTINUES!!",
        guideStepSkip: "SKIPPED!! WE SHALL RETURN TO IT!! NOTHING ESCAPES MY PROTOCOLS!!",
        guideComplete: "ALL PRESCRIPTIONS REVIEWED!! THE TREATMENT PROTOCOL IS COMPLETE!! NOW OPERATE!!",
        guideManualMode: "MANUAL MODE!! YOU THINK YOU CAN DO BETTER?! PROVE IT!!",
        guideResume: "RESUMING GUIDED MODE!! BACK UNDER MY SUPERVISION!! WHERE YOU BELONG!!",
        // ── Doctor's Notes ──
        doctorNoteClean: "THE PATIENT IS PERFECT!! {passCount} CHECKS PASSED ACROSS {relayCount} RELAY(S)!! A FLAWLESS SPECIMEN!! NO INTERVENTION NEEDED!! *adjusts monocle*",
        doctorNoteMinor: "ACCEPTABLE!! {warnCount} MINOR OBSERVATION(S)!! {passCount} PASSED!! Nothing CRITICAL but PERFECTION DEMANDS ATTENTION TO DETAIL!!",
        doctorNoteCritical: "CATASTROPHIC!! {failCount} FAILURE(S)!! {warnCount} WARNING(S)!! MULTIPLE SYSTEMS COMPROMISED!! TO THE OPERATING ROOM!! IMMEDIATELY!!",
        doctorNoteRelayConfig: "THE RELAY URLS ARE CORRUPTED!! Invalid addresses!! DISCOVERY IMPOSSIBLE!! FIX THEM FIRST!! THE EXPERIMENT CANNOT PROCEED WITHOUT VALID INFRASTRUCTURE!!",
        doctorNoteSync: "DATA FRAGMENTATION DETECTED!! RELAYS CARRY CONFLICTING VERSIONS!! A REBROADCAST WILL RESTORE ORDER!! THIS IS THE PRIMARY INTERVENTION!!",
        doctorNoteMarmot: "MARMOT PROTOCOL INCOMPLETE!! KIND 10050 AND 10051 ARE MISSING!! WITHOUT THEM, ENCRYPTED MESSAGING IS IMPOSSIBLE!! PUBLISH THEM!! NOW!!",
        doctorNoteKeyPackage: "KEYPACKAGES FAIL MIP-00/01!! ENCODING!! EXTENSIONS!! CIPHERSUITES!! ALL NON-COMPLIANT!! The originating client MUST republish!! THIS IS BEYOND MY OPERATING TABLE!!",
        doctorNoteMultiple: "{categoryCount} CATEGORIES OF FAILURE!! START WITH RELAY AND SYNC!! THEN MARMOT!! FOLLOW THE TREATMENT PLAN!! TOP!! TO!! BOTTOM!!",
    },
    daimon: {
        intro: "I am Daimon. Enter an npub. I will run the diagnostic. I never fail. *adjusts scrub cap*",
        invalidNpub: "That is not a valid npub. npub1, 63 characters. Try again.",
        decodeFail: "Decode failed. Verify the npub.",
        auditStart: "Initiating diagnostic for {npub}. Proceed.",
        auditStartNip07: "NIP-07 verified. Initiating diagnostic for {npub}.",
        takingPulse: "Taking your pulse. Connecting to bootstrap relays.",
        relayFound: "Found <span class=\"hi\">{count}</span> relay(s). Querying.",
        relayInvalid: "<span class='err'>All {count} URLs invalid.</span> Using fallback relays.",
        noRelays: "No relay lists. Using bootstrap relays.",
        examiningSync: "All relays queried. Examining sync.",
        vitalSigns: "Checking vital signs.",
        nip05Verify: "Verifying NIP-05.",
        vitalGaps: "Vital signs: {count} issue(s).",
        vitalWarn: "Profile basics present; {count} optional field(s) could help.",
        vitalOk: "Vital signs acceptable.",
        singleRelay: "<span class=\"warn\">Single relay</span> — add 2–3 more.",
        relayReachable: "<span class=\"warn\">{reachable} of {total} reachable</span> — some failed.",
        profileStale: "Profile {days} days old. Refresh.",
        contactsStale: "Contacts {days} days old. Rebroadcast.",
        kpNoOverlap: "KeyPackage relays not in main list. Inviters may need extra relays.",
        inboxRelayCheck: "Checking inbox relays.",
        no10050: "No <span class='err'>kind 10050</span>. Giftwrap delivery impossible.",
        inboxRelaysFound: "Found <span class=\"hi\">{count}</span> Inbox relay(s).",
        inboxNoOverlap: "Inbox relays not in NIP-65. Split delivery risk.",
        crossedWires: "<span class=\"err\">⚠ Crossed wires.</span> {count} relay(s): {named}{extras}. Rebroadcast.",
        perfectSync: "<span class=\"ok\">✔ Sync correct.</span> All {count} relay(s) match.",
        marmotPanel: "Marmot Protocol — MIP-00 / MIP-01.",
        marmotPanelSync: "Marmot Protocol. Rebroadcast will help KeyPackage propagation.",
        no10051: "No <span class='err'>kind 10051</span>. Marmot unavailable until you publish one.",
        kpRelaysFound: "Found <span class=\"hi\">{count}</span> KeyPackage relay(s). Fetching.",
        kpNone: "Kind 10051: {count} relay(s), <span class='err'>no KeyPackages</span>. Publish one.",
        kpAllPass: "All <span class=\"ok\">{count} KeyPackage(s)</span> pass.",
        kpSomeFail: "<span class=\"err\">{count} failed</span>{hint}.",
        orphanedKps: "KeyPackages on {count} relay(s) outside k10051. Stranded.",
        charting: "Final diagnosis.",
        success: "Diagnosis complete. <span class='ok'>Clean.</span> {relays} relay(s), {kp} KeyPackage(s). Discharged.",
        minorWarn: "Diagnosis complete. {count} minor issue(s). Follow prescription.",
        rebroadcastStart: "Rebroadcasting. Stand by.",
        rebroadcastProgress: "{done} of {total} relay(s).",
        rebroadcastDone: "<span class='ok'>Done.</span> {count} relay(s) updated.",
        rebroadcastFail: "{succeeded} ok, {failed} failed. Relays are unreliable.",
        deleteKpStart: "Deleting {count} KeyPackage(s).",
        deleteKpSign: "NIP-07 signature. Approve.",
        deleteKpDone: "<span class='ok'>Deleted.</span> {count} gone. Publish replacements.",
        deleteKpFail: "<span class='err'>Failed.</span> Extension or relay error.",
        noNip07ForAction: "NIP-07 required. Install an extension.",
        nextPatient: "Next patient. Enter an npub.",
        relayDivergence: "<span class='warn'>Relay divergence.</span> {k3Only} relay(s) only in k3, "
            + "{k10002Only} only in k10002. Unify them.",
        unifyRelaysStart: "Merging k3 and k10002 relay lists. Broadcasting.",
        unifyRelaysDone: "<span class='ok'>Done.</span> {count} relay(s) updated. k3 and k10002 now carry "
            + "{total} relay(s).",
        // ── Operating Room ──
        orIntro: "Operating Room. I will fix what is broken. *adjusts scrub cap*",
        orRequiresNip07: "NIP-07 required. Cannot operate without authentication.",
        orHealthStart: "Diagnostics. Stand by.",
        orHealthGood: "<span class='ok'>{count} relay(s) online.</span> Acceptable.",
        orHealthSlow: "<span class='warn'>{count} slow.</span> Operable.",
        orHealthDead: "<span class='err'>{count} dead.</span> Remove them.",
        orDiscard: "Discarded.",
        orClose: "Done.",
        orOperateStart: "<span class='hi'>{count}</span> procedure(s). {changes} changes. Sign.",
        orProcedure: "Procedure {index}/{total}: {name}.",
        orProcedureOk: "<span class='ok'>{name}</span> — {succeeded} relay(s).",
        orProcedureFail: "<span class='err'>{name}</span> — {failed} rejected.",
        orSuccess: "<span class='ok'>Complete.</span> {procedures} procedure(s). {relays} relay(s). Clean.",
        orPartial: "{succeeded} ok. {failed} failed.",
        orFail: "<span class='err'>Failed.</span> No relays accepted.",
        // ── OR Briefing & Auto-Stage ──
        orBriefingAutoStaged: "Pre-staged <span class='hi'>{staged}</span> fix(es). Review. Adjust if needed.",
        orBriefingSuggestions: "<span class='warn'>{count}</span> item(s) need your decision.",
        orBriefingGuided: "<span class='hi'>{steps}</span> steps in the treatment plan. Follow or go manual.",
        // ── Guided Mode ──
        guideStepNote: "Step {step}/{total}.",
        guideStepAdvance: "Step {step}/{total}. Next.",
        guideStepSkip: "Skipped.",
        guideComplete: "Plan complete. Operate when ready.",
        guideManualMode: "Manual mode.",
        guideResume: "Resuming guided mode.",
        // ── Doctor's Notes ──
        doctorNoteClean: "{passCount} checks passed. {relayCount} relay(s). Clean. No intervention.",
        doctorNoteMinor: "{warnCount} minor issue(s). {passCount} passed. Address when convenient.",
        doctorNoteCritical: "{failCount} critical. {warnCount} warnings. Operating Room recommended.",
        doctorNoteRelayConfig: "Relay URLs are invalid. Fix those first. Everything depends on them.",
        doctorNoteSync: "Out of sync. Rebroadcast. That's the fix.",
        doctorNoteMarmot: "Marmot incomplete. Publish k10050 and k10051.",
        doctorNoteKeyPackage: "KeyPackages non-compliant. Client needs to republish.",
        doctorNoteMultiple: "{categoryCount} categories. Fix relay/sync first, then Marmot.",
    },
    jeff: {
        intro: "Enter an npub to run a diagnostic: relay discovery, sync verification, MIP-00/01 compliance, and profile vitals. Or use NIP-07 to sign in.",
        invalidNpub: "Invalid npub. Expected format: npub1 followed by ~63 characters.",
        decodeFail: "Failed to decode npub. Verify the value and try again.",
        auditStart: "Running diagnostic for {npub}.",
        auditStartNip07: "NIP-07 identity verified. Running diagnostic for {npub}.",
        takingPulse: "Connecting to bootstrap relays to discover relay list.",
        relayFound: "Found <span class=\"hi\">{count}</span> relay(s). Querying for latest events.",
        relayInvalid: "<span class='err'>All {count} relay URL(s) invalid.</span> Using fallback relays.",
        noRelays: "No relay lists found in k3/k10002/k10051. Using bootstrap relays.",
        examiningSync: "Checking relay synchronization.",
        vitalSigns: "Checking profile vitals: name, picture, NIP-05.",
        nip05Verify: "Verifying NIP-05.",
        vitalGaps: "{count} issue(s) found in profile vitals.",
        vitalWarn: "Profile basics present. {count} optional field(s) could be added.",
        vitalOk: "Profile vitals OK.",
        singleRelay: "<span class=\"warn\">Single relay configured.</span> Add 2\u20133 more for redundancy.",
        relayReachable: "<span class=\"warn\">{reachable} of {total} relay(s) reachable.</span>",
        profileStale: "Profile last updated {days} days ago.",
        contactsStale: "Contacts list is {days} days old.",
        kpNoOverlap: "KeyPackage relays are not in the main relay list.",
        inboxRelayCheck: "Checking inbox relays for giftwrap delivery.",
        no10050: "No <span class='err'>kind 10050</span> found. Giftwrap delivery not possible.",
        inboxRelaysFound: "Found <span class=\"hi\">{count}</span> inbox relay(s).",
        inboxNoOverlap: "Inbox relays (k10050) do not overlap with NIP-65 relays (k10002).",
        crossedWires: "<span class=\"err\">Sync issue:</span> {count} relay(s) have stale or missing data: {named}{extras}. Rebroadcast recommended.",
        perfectSync: "<span class=\"ok\">Sync OK.</span> Profile and contacts identical across all {count} relay(s).",
        marmotPanel: "Running MIP-00/MIP-01 compliance scan.",
        marmotPanelSync: "Running MIP-00/MIP-01 compliance scan. Rebroadcasting will help KeyPackage propagation.",
        no10051: "No <span class='err'>kind 10051</span> found. KeyPackage relay advertisement not available.",
        kpRelaysFound: "Found <span class=\"hi\">{count}</span> KeyPackage relay(s). Fetching KeyPackages (kind 443).",
        kpNone: "Kind 10051 lists {count} relay(s) but <span class='err'>no KeyPackages (k443)</span> found.",
        kpAllPass: "All <span class=\"ok\">{count} KeyPackage(s)</span> pass MIP-00/01 validation.",
        kpSomeFail: "<span class=\"err\">{count} KeyPackage(s) failed</span> validation{hint}",
        orphanedKps: "<span class='warn'>KeyPackage(s) found on {count} relay(s) outside kind 10051 list.</span> These will not be discovered.",
        charting: "Compiling results.",
        success: "Diagnostic complete. <span class='ok'>No issues found.</span> {relays} relay(s), {kp} KeyPackage(s), all synchronized.",
        minorWarn: "Diagnostic complete. {count} minor issue(s) found.",
        failure: "Diagnostic complete. <span class='err'>{count} critical issue(s).</span> {message}",
        rebroadcastStart: "Rebroadcasting profile and contacts to all relays.",
        rebroadcastProgress: "<span class='hi'>{done}</span> of {total} relay(s) updated.",
        rebroadcastDone: "<span class='ok'>Rebroadcast complete.</span> {count} relay(s) updated.",
        rebroadcastFail: "Partial failure: <span class='ok'>{succeeded} succeeded</span>, <span class='err'>{failed} failed</span>.",
        deleteKpStart: "Deleting {count} invalid KeyPackage(s).",
        deleteKpSign: "NIP-07 signature required. Approve the signing request.",
        deleteKpDone: "<span class='ok'>Deleted.</span> {count} KeyPackage deletion event(s) broadcast.",
        deleteKpFail: "<span class='err'>Deletion failed.</span> Extension declined or relay error.",
        noNip07ForAction: "This action requires a <span class='hi'>NIP-07 extension</span>.",
        noAuditData: "No audit data. Run a diagnostic first.",
        nextPatient: "Enter an npub or use NIP-07 to run another diagnostic.",
        relayDivergence: "<span class='warn'>Relay list divergence:</span> {k3Only} relay(s) only in k3, {k10002Only} only in k10002.",
        unifyRelaysStart: "Merging k3 and k10002 relay lists.",
        unifyRelaysDone: "<span class='ok'>Relay lists unified.</span> {count} relay(s) updated with {total} relay(s) each.",
        // ── Doctor's Notes ──
        doctorNoteClean: "Diagnostic complete. {passCount} checks passed across {relayCount} relay(s). No issues found. No action required.",
        doctorNoteMinor: "{warnCount} minor issue(s) detected. {passCount} checks passed. Address when convenient.",
        doctorNoteCritical: "{failCount} critical issue(s) and {warnCount} warning(s) detected. Review treatment plan for resolution steps.",
        doctorNoteRelayConfig: "Invalid relay URLs detected. Fix relay addresses first — other checks depend on valid relay configuration.",
        doctorNoteSync: "Profile and contacts out of sync across relays. Rebroadcast to restore consistency.",
        doctorNoteMarmot: "Marmot Protocol configuration incomplete. Publish kind 10050 and/or 10051 to enable encrypted messaging.",
        doctorNoteKeyPackage: "KeyPackage validation failures per MIP-00/01. Originating client needs to republish corrected KeyPackages.",
        doctorNoteMultiple: "{categoryCount} categories of issues detected. Address relay configuration and sync first, then Marmot Protocol setup.",
    },
    house: {
        intro: "Give me an npub. I'll run a diagnostic. Everybody lies, especially metadata. *leans on cane*",
        invalidNpub: "That's not an npub. It's a lie. npub1, 63 chars. Try again.",
        decodeFail: "Couldn't decode it. Either you're wrong or it's wrong. Probably both.",
        auditStart: "Fine. Diagnostic for {npub}. Don't expect good news.",
        auditStartNip07: "NIP-07. Fine. Diagnostic for {npub}.",
        takingPulse: "Taking your pulse. Connecting to relays. They'll probably lie too.",
        relayFound: "Found <span class=\"hi\">{count}</span> relay(s). Querying. We'll see what they're hiding.",
        relayInvalid: "<span class='err'>All {count} URLs invalid.</span> Nice. Using fallback.",
        noRelays: "No relay lists. Of course. Using bootstrap.",
        examiningSync: "Queries done. Looking for crossed wires. There are always crossed wires.",
        vitalSigns: "Vital signs. Name, picture, NIP-05. The usual lies.",
        nip05Verify: "Verifying NIP-05. It's probably lying.",
        vitalGaps: "Vital signs: {count} problems. Shocking.",
        vitalWarn: "Profile basics present. {count} optional fields. Whatever.",
        vitalOk: "Vital signs... acceptable. For now.",
        singleRelay: "<span class=\"warn\">Single relay.</span> One outage and you're dead. Add more.",
        relayReachable: "<span class=\"warn\">{reachable} of {total} reachable.</span> Some didn't respond. Surprise.",
        profileStale: "Profile {days} days old. Refresh. Or don't.",
        contactsStale: "Contacts {days} days old. Rebroadcast. If you care.",
        kpNoOverlap: "KeyPackage relays aren't in your main list. Inviters might not find you. Great.",
        inboxRelayCheck: "Inbox relays. Let's see if giftwraps can even reach you.",
        no10050: "No <span class='err'>kind 10050</span>. Giftwraps can't find you. Shocking. Publish one. Or don't.",
        inboxRelaysFound: "Found <span class=\"hi\">{count}</span> Inbox relay(s). At least something works.",
        inboxNoOverlap: "Inbox relays aren't in your NIP-65 list. Giftwraps might get lost. Typical.",
        crossedWires: "<span class=\"err\">⚠ Crossed wires. What a surprise.</span> {count} relay(s): {named}{extras}. Rebroadcast. Or don't. See if I care.",
        perfectSync: "<span class=\"ok\">✔ Sync is fine.</span> For once. All {count} relay(s) match.",
        marmotPanel: "Marmot Protocol. MIP-00, MIP-01. Let's see how broken this is.",
        marmotPanelSync: "Marmot Protocol. Those sync issues? Rebroadcast. Might help.",
        no10051: "No <span class='err'>kind 10051</span>. Marmot won't work. Publish one. Or don't.",
        kpRelaysFound: "Found <span class=\"hi\">{count}</span> KeyPackage relay(s). Fetching. Probably all wrong.",
        kpNone: "Kind 10051 has {count} relay(s) but <span class='err'>no KeyPackages</span>. Publish one. Obviously.",
        kpAllPass: "All <span class=\"ok\">{count} KeyPackage(s)</span> pass. Huh. That's rare.",
        kpSomeFail: "<span class=\"err\">{count} failed</span>{hint}. Obviously.",
        orphanedKps: "KeyPackages on {count} relay(s) that aren't in your k10051. "
            + "Stranded. Nobody will find them. Great.",
        charting: "Final diagnosis. Brace yourself.",
        success: "Diagnosis complete. <span class='ok'>Clean.</span> {relays} relay(s), {kp} KeyPackage(s). Don't let it go to your head. Discharged.",
        minorWarn: "Diagnosis complete. {count} minor issue(s). Fix them. Or don't.",
        failure: "Diagnosis complete. <span class='err'>{count} critical issue(s).</span> What did you expect? {message}",
        rebroadcastStart: "Rebroadcasting your profile. Don't get excited.",
        rebroadcastProgress: "{done} of {total}. Thrilling.",
        rebroadcastDone: "<span class='ok'>Done.</span> {count} relay(s) updated. You're welcome. Not that you asked.",
        rebroadcastFail: "{succeeded} worked, {failed} didn't. Relays. Can't live with them. Can't live without them.",
        deleteKpStart: "Deleting {count} broken KeyPackage(s). Finally, something I can fix.",
        deleteKpSign: "NIP-07 wants your approval. Try not to mess this up.",
        deleteKpDone: "<span class='ok'>{count} KeyPackage(s) deleted.</span> Publish new ones. Correctly, this time.",
        deleteKpFail: "<span class='err'>Failed.</span> Extension declined. Even your browser doesn't trust you.",
        noNip07ForAction: "Need NIP-07 for this. Install an extension. I'll wait. *pops vicodin*",
        nextPatient: "Next patient. Because apparently one isn't enough suffering for today. *limps to whiteboard*",
        relayDivergence: "<span class='warn'>Relay divergence. Shocking.</span> {k3Only} relay(s) only in k3, "
            + "{k10002Only} only in k10002. Your clients are picking different relay sets. Classic. "
            + "Unify them.",
        unifyRelaysStart: "Merging your relay lists. Try not to screw it up. *signs NIP-07 request*",
        unifyRelaysDone: "<span class='ok'>Done.</span> {count} relay(s) updated. k3 and k10002 now agree on "
            + "{total} relay(s). "
            + "First time for everything.",
        // ── Operating Room ──
        orIntro: "Operating Room. Finally, something interesting. *snaps on gloves* Don't flinch.",
        orRequiresNip07: "Can't operate without NIP-07. Even I need consent. Usually. *pops vicodin*",
        orHealthStart: "Pinging your relays. Let's see which ones are still pretending to work.",
        orHealthGood: "<span class='ok'>All {count} relay(s) alive.</span> Shocking. Usually at least one is dead. Don't get used to it.",
        orHealthSlow: "<span class='warn'>{count} relay(s) dragging their feet.</span> Like my interns. We'll manage.",
        orHealthDead: "<span class='err'>{count} relay(s) flatlined.</span> Time of death: now. Remove them or pretend they don't exist. Your call.",
        orDiscard: "All changes gone. Like they never happened. Story of my life.",
        orClose: "Leaving the OR. Try not to break anything while I'm gone. *limps out*",
        orOperateStart: "<span class='hi'>{count}</span> procedure(s). {changes} changes. I'll need your NIP-07 signature. Try not to overthink it.",
        orProcedure: "Procedure {index} of {total}: <span class='hi'>{name}</span>. Hold still.",
        orProcedureOk: "<span class='ok'>{name}</span> — {succeeded} relay(s) cooperated. A miracle.",
        orProcedureFail: "<span class='err'>{name} — {failed} relay(s) said no.</span> Of course they did.",
        orSuccess: "<span class='ok'>Surgery complete.</span> {procedures} procedure(s), {relays} relay(s). Everything worked. I'm as surprised as you are. *tosses gloves dramatically*",
        orPartial: "{succeeded} worked. {failed} didn't. Like most things in life. You're welcome.",
        orFail: "<span class='err'>Complete failure.</span> Not a single relay cooperated. Everybody lies. Especially relays.",
        // ── OR Briefing & Auto-Stage ──
        orBriefingAutoStaged: "I've already figured out <span class='hi'>{staged}</span> fix(es) for you. You're welcome. Check below — or don't. See if I care.",
        orBriefingSuggestions: "<span class='warn'>{count}</span> thing(s) I can't auto-fix. Shocking. Even geniuses have limits. *pops vicodin*",
        orBriefingGuided: "Made you a <span class='hi'>{steps}-step</span> plan. Because apparently you need hand-holding. Follow it or don't. Your funeral.",
        // ── Guided Mode ──
        guideStepNote: "Step {step} of {total}. Try not to break anything.",
        guideStepAdvance: "Step {step} of {total}. You're actually following instructions. Novel.",
        guideStepSkip: "Skipping. Fine. It's not like I spent time on that prescription or anything.",
        guideComplete: "We're through the plan. Now review what you've staged and operate. Or don't. But then why are we here?",
        guideManualMode: "Manual mode. You think you know better. You probably don't. But go ahead. *leans on cane*",
        guideResume: "Back to guided mode. Couldn't handle freedom, could you? *smirks*",
        // ── Doctor's Notes ──
        doctorNoteClean: "Against all odds, the patient is healthy. {passCount} checks passed across {relayCount} relay(s). Everything works. I'm almost disappointed — no puzzles to solve. Almost. *leans back* Discharged.",
        doctorNoteMinor: "{warnCount} minor issue(s). Not going to kill you. {passCount} things actually work. Fix the warnings when you feel like pretending to care about your relay health.",
        doctorNoteCritical: "{failCount} critical failure(s). {warnCount} warnings. What a mess. You need the operating room. Follow the treatment plan — and for once, do exactly what I say.",
        doctorNoteRelayConfig: "Your relay URLs are broken. That's like giving people your address but writing it in hieroglyphics. Fix the URLs. Everything else is pointless until you do.",
        doctorNoteSync: "Your data is inconsistent across relays. Some have your profile from last year, others from yesterday. Rebroadcast. It's not rocket science. Even you can manage that.",
        doctorNoteMarmot: "Marmot Protocol isn't set up. Missing k10050 or k10051 — that's like having a phone with no SIM card. Publish the missing events. Or enjoy the silence.",
        doctorNoteKeyPackage: "KeyPackages are broken. MIP-00/01 says they're wrong, and MIP-00/01 doesn't lie. Unlike everybody else. Your client needs to fix and republish them. I can't do that from here.",
        doctorNoteMultiple: "{categoryCount} different categories of failure. Impressive, really. Start with relay and sync problems — everything else depends on those working. Then Marmot. Follow the plan. It's in order for a reason.",
    },
};

/** Resolve style (bubbly inherits from sunny) */
function getLines(style) {
    const s = style || spritePanel?.dataset?.spriteStyle || 'marmot';
    const lines = LINES[s] ?? LINES.marmot;
    if (s === 'bubbly') return { ...LINES.sunny, ...lines };
    return lines;
}

export function speak(key, vars = {}) {
    if (isJeff) {
        const text = LINES.jeff[key] ?? LINES.marmot[key];
        if (!text) return null;
        return fmt(text, vars);
    }
    const style = spritePanel?.dataset?.spriteStyle || 'marmot';
    const lines = getLines(style);
    let text = lines[key] ?? LINES.marmot[key];
    if (!text) return null;
    return fmt(text, vars);
}
