/**
 * Personality-driven speech for each Dr. Marmot variant.
 * speak(key, vars) returns the appropriate line for the active style.
 */

import { spritePanel } from './dom.js';

const STYLE_NAMES = {
    marmot: 'Dr. Marmelade Marmot',
    sunny: 'Dr. Sunny Marmot',
    bubbly: 'Dr. Bubbly Marmot',
    professor: 'Dr. Professor Marmot',
    sparky: 'Dr. Sparky Marmot',
    nuts: 'Dr. Nuts Marmot',
    daimon: 'Dr. Daimon Marmot',
    house: 'Dr. Gregory Marmot',
};

export function getDisplayName() {
    const style = spritePanel?.dataset?.spriteStyle || 'marmot';
    return STYLE_NAMES[style] ?? 'Dr. Marmot';
}

function fmt(template, vars) {
    return template.replace(/\{(\w+)\}/g, (_, k) => String(vars[k] ?? ''));
}

const LINES = {
    marmot: {
        intro: "Hello! I am Doctor Marmot. Enter an npub and I'll run a full diagnostic: relay discovery from k3/k10002/k10051, sync verification across relays, Marmot Protocol (MIP-00/01) compliance, and vital signs. Paste an npub or use NIP-07. *adjusts stethoscope*",
        invalidNpub: "Hmm, that doesn't look like a valid npub. It should start with npub1 and be about 63 characters long.",
        decodeFail: "I couldn't decode that npub. Are you sure it's correct?",
        auditStart: "Very well. Initiating full diagnostic for patient {npub}...",
        auditStartNip07: "Ah, NIP-07! Identity verified by extension. Very well — initiating full diagnostic for patient {npub}...",
        takingPulse: "Taking your pulse... connecting to bootstrap relays to discover your relay list.",
        relayFound: "Found <span class=\"hi\">{count}</span> relay(s) in your metadata. Querying each for your latest events...",
        relayInvalid: "Relay tags present but <span class='err'>all {count} URL(s) invalid</span> — malformed wss:// or hostnames. Falling back to standard relays.",
        noRelays: "No relay lists in k3 / k10002 / k10051. Using bootstrap relays — consider advertising your relays for better client discovery.",
        examiningSync: "All relays queried. Examining for crossed wires and sync anomalies...",
        vitalSigns: "Checking vital signs: name, picture, NIP-05...",
        nip05Verify: "Contacting NIP-05 server to verify...",
        vitalGaps: "Vital signs show gaps — {count} issue(s) that may affect identity verification or client compatibility.",
        vitalWarn: "Profile basics present; {count} optional field(s) could strengthen your identity (NIP-05, about, picture).",
        vitalOk: "Vital signs healthy — name, picture, and identity markers look good.",
        singleRelay: "<span class=\"warn\">Single relay</span> — one outage and your profile is unreachable. Add 2–3 more relays for redundancy.",
        relayReachable: "<span class=\"warn\">{reachable} of {total} relay(s) reachable</span> — some failed to respond. Check relay status or firewall.",
        profileStale: "Profile last updated {days} days ago — consider refreshing if your details have changed.",
        contactsStale: "Contacts list is {days} days old — rebroadcast if you've added new follows.",
        kpNoOverlap: "KeyPackage relays aren't in your main relay list — inviters may need to connect to extra relays to find you.",
        crossedWires: "<span class=\"err\">⚠ CROSSED WIRES!</span> {count} relay(s) showing stale or missing data: {named}{extras}. A rebroadcast of your profile and contacts will bring them into sync.",
        perfectSync: "<span class=\"ok\">✔ Perfect sync</span> — Profile and Contacts identical across all {count} relay(s). Excellent consistency.",
        marmotPanel: "Now running the Marmot Protocol panel — MIP-00 / MIP-01 compliance scan...",
        marmotPanelSync: "Now running the Marmot Protocol panel — MIP-00 / MIP-01 compliance scan. I noticed sync issues earlier — rebroadcasting will help KeyPackage propagation.",
        no10051: "No <span class='err'>kind 10051</span> found — this profile cannot advertise KeyPackage relays. Marmot messaging unavailable until you publish one.",
        kpRelaysFound: "Found <span class=\"hi\">{count}</span> KeyPackage relay(s). Fetching KeyPackages (kind 443)...",
        kpNone: "Kind 10051 lists {count} relay(s), but <span class='err'>no KeyPackages (k443)</span> found. Your client must publish at least one to receive Marmot DMs.",
        kpAllPass: "All <span class=\"ok\">{count} KeyPackage(s)</span> pass MIP-00/01. Marmot protocol compliant.",
        kpSomeFail: "<span class=\"err\">{count} KeyPackage(s) failed</span> validation{hint}",
        charting: "Charting the final diagnosis...",
        success: "Diagnosis complete. <span class='ok'>Clean bill of health!</span> {relays} relay(s), {kp} KeyPackage(s), all in sync and Marmot-ready. Patient discharged.",
        minorWarn: "Diagnosis complete. {count} minor issue(s) — nothing critical. Follow the prescription above when convenient.",
        failure: "Diagnosis complete. <span class='err'>{count} critical issue(s).</span> {message}",
        rebroadcastStart: "Administering treatment — rebroadcasting your Profile and Contacts to all relays...",
        rebroadcastProgress: "<span class='hi'>{done}</span> of {total} relay(s) updated...",
        rebroadcastDone: "<span class='ok'>Rebroadcast complete.</span> {count} relay(s) now carry your latest data. Sync restored.",
        rebroadcastFail: "Rebroadcast partially failed — <span class='ok'>{succeeded} succeeded</span>, <span class='err'>{failed} failed</span>. Check those relays.",
        deleteKpStart: "Preparing deletion events for <span class='hi'>{count}</span> broken KeyPackage(s)...",
        deleteKpSign: "Requesting signature from your NIP-07 extension — please approve the signing request.",
        deleteKpDone: "<span class='ok'>Done.</span> {count} KeyPackage deletion event(s) broadcast. Publish fresh KeyPackages with correct tags.",
        deleteKpFail: "<span class='err'>Deletion failed</span> — extension declined or relay error. Try again.",
        noNip07ForAction: "This action requires a <span class='hi'>NIP-07 extension</span> to sign events. Install nos2x, Alby, or similar.",
        noAuditData: "No audit data available. Run a diagnostic first.",
        nextPatient: "Next patient, please! Enter an npub or use NIP-07 and I'll run a full diagnostic.",
        relayDivergence: "<span class='warn'>Relay divergence detected.</span> {k3Only} relay(s) only in Contacts (k3), {k10002Only} only in NIP-65 (k10002). Different clients will see different relay lists — unify them.",
        unifyRelaysStart: "Merging your k3 and k10002 relay lists into a single unified set and broadcasting to all relays...",
        unifyRelaysDone: "<span class='ok'>Relay lists unified.</span> {count} relay(s) now carry a consistent k3 and k10002 with {total} relay(s) each.",
    },
    sunny: {
        intro: "Hi!! I'm Sunny! 🌞 Paste an npub and I'll check everything — relays, sync, Marmot stuff, the works! Let's go!!",
        invalidNpub: "Ooh, that doesn't look right... npub should start with npub1 and be ~63 chars!",
        decodeFail: "Hmm, I couldn't decode that. Double-check it for me?",
        auditStart: "Yay! Let's do this!! Full diagnostic for {npub}... here we go!",
        auditStartNip07: "Ooh, NIP-07! You're all verified! Running full diagnostic for {npub}...",
        takingPulse: "Taking your pulse... *bounce* Connecting to relays to find your list!",
        relayFound: "Found <span class=\"hi\">{count}</span> relay(s)! That's so many! Checking them all...",
        relayInvalid: "Uh-oh, <span class='err'>all {count} URLs are invalid</span>... Using fallback relays instead.",
        noRelays: "No relay lists found. Using bootstrap relays — you should add yours someday!",
        examiningSync: "Done querying! Now checking for crossed wires and sync stuff...",
        vitalSigns: "Checking your vital signs — name, picture, NIP-05!",
        nip05Verify: "Pinging NIP-05 server...",
        vitalGaps: "Vital signs have {count} gap(s). Might affect identity stuff.",
        vitalWarn: "Profile basics ok; {count} optional field(s) could help (NIP-05, about, picture).",
        vitalOk: "Vital signs look great! ✨",
        singleRelay: "<span class=\"warn\">Single relay</span> — add 2–3 more for redundancy!",
        relayReachable: "<span class=\"warn\">{reachable} of {total} relay(s) reachable</span> — some didn't respond.",
        profileStale: "Profile updated {days} days ago — refresh if you've changed stuff!",
        contactsStale: "Contacts {days} days old — rebroadcast if you've added follows!",
        kpNoOverlap: "KeyPackage relays aren't in your main list — inviters might need extra relays to find you!",
        crossedWires: "<span class=\"err\">⚠ Oops, crossed wires!</span> {count} relay(s) have stale data: {named}{extras}. Rebroadcast to fix!",
        perfectSync: "<span class=\"ok\">✔ Perfect sync!!</span> All {count} relay(s) match. So consistent!",
        marmotPanel: "Now the Marmot Protocol part — MIP-00 / MIP-01!",
        marmotPanelSync: "Marmot Protocol scan! (Also — rebroadcast will help with those sync issues we saw.)",
        no10051: "No <span class='err'>kind 10051</span>... Can't advertise KeyPackage relays. Marmot DMs won't work until you add one!",
        kpRelaysFound: "Ooh! <span class=\"hi\">{count}</span> KeyPackage relay(s)! Fetching KeyPackages...",
        kpNone: "Kind 10051 has {count} relay(s) but <span class='err'>no KeyPackages (k443)</span>. Your client needs to publish at least one!",
        kpAllPass: "All <span class=\"ok\">{count} KeyPackage(s)</span> pass! Marmot compliant!!",
        kpSomeFail: "<span class=\"err\">{count} KeyPackage(s) failed</span>{hint}",
        charting: "Writing up the diagnosis...",
        success: "All done!! <span class='ok'>Clean bill of health!</span> {relays} relay(s), {kp} KeyPackage(s), everything synced! Patient discharged! 🌟",
        minorWarn: "Done! {count} minor thing(s) — nothing scary. Fix when you can!",
        rebroadcastStart: "Ooh! Let me fix this — rebroadcasting your profile and contacts!",
        rebroadcastProgress: "<span class='hi'>{done}</span> of {total} relay(s) done!",
        rebroadcastDone: "<span class='ok'>All synced up!</span> {count} relay(s) updated! ✨",
        rebroadcastFail: "Hmm, some relays didn't cooperate — <span class='ok'>{succeeded} ok</span>, <span class='err'>{failed} failed</span>.",
        deleteKpStart: "Deleting {count} broken KeyPackage(s)!",
        deleteKpSign: "Need your NIP-07 extension to sign — please approve!",
        deleteKpDone: "<span class='ok'>Deleted!</span> {count} KeyPackage(s) gone! Now publish fresh ones!",
        deleteKpFail: "<span class='err'>Delete failed</span> — extension said no or relay error.",
        noNip07ForAction: "Need a <span class='hi'>NIP-07 extension</span> for this! Install one first!",
        nextPatient: "Next patient! Let's go!! Paste an npub or use NIP-07!",
    },
    bubbly: {
        /* inherits from sunny */
    },
    professor: {
        intro: "Good day. I am Professor Grey. Present an npub and I shall conduct a comprehensive diagnostic: relay discovery via k3/k10002/k10051, synchronization verification, Marmot Protocol compliance, and vital sign assessment. Proceed.",
        invalidNpub: "That does not resemble a valid npub. It ought to commence with npub1 and approximate 63 characters in length.",
        decodeFail: "Decoding failed. Kindly verify the npub's correctness.",
        auditStart: "Very well. Initiating full diagnostic for patient {npub}.",
        auditStartNip07: "NIP-07 verification confirmed. Initiating full diagnostic for patient {npub}.",
        takingPulse: "Taking your pulse. Establishing connections to bootstrap relays for relay discovery.",
        relayFound: "Located <span class=\"hi\">{count}</span> relay(s) in metadata. Querying each for the latest events.",
        relayInvalid: "Relay tags present; however, <span class='err'>all {count} URL(s) invalid</span>. Malformed wss:// or hostnames. Employing standard relay fallback.",
        noRelays: "No relay lists in k3 / k10002 / k10051. Using bootstrap relays. Consider advertising your relays.",
        examiningSync: "Relay queries complete. Examining for crossed wires and synchronization anomalies.",
        vitalSigns: "Assessing vital signs: name, picture, NIP-05.",
        nip05Verify: "Contacting NIP-05 server for verification.",
        vitalGaps: "Vital signs indicate {count} gap(s) that may affect identity verification.",
        vitalWarn: "Profile basics present; {count} optional field(s) could strengthen identity.",
        vitalOk: "Vital signs satisfactory — name, picture, identity markers acceptable.",
        singleRelay: "<span class=\"warn\">Single relay</span> — one outage and profile unreachable. Add 2–3 more.",
        relayReachable: "<span class=\"warn\">{reachable} of {total} relay(s) reachable</span> — some failed to respond.",
        profileStale: "Profile last updated {days} days ago. Refresh if details have changed.",
        contactsStale: "Contacts list {days} days old. Rebroadcast if new follows added.",
        kpNoOverlap: "KeyPackage relays not in main relay list — inviters may need extra relays.",
        crossedWires: "<span class=\"err\">⚠ CROSSED WIRES DETECTED.</span> {count} relay(s) exhibiting stale or missing data: {named}{extras}. A rebroadcast is recommended.",
        perfectSync: "<span class=\"ok\">✔ Synchronization satisfactory.</span> Profile and Contacts identical across all {count} relay(s).",
        marmotPanel: "Proceeding to Marmot Protocol panel — MIP-00 / MIP-01 compliance scan.",
        marmotPanelSync: "Marmot Protocol panel. Earlier sync anomalies noted — rebroadcasting will facilitate KeyPackage propagation.",
        no10051: "No <span class='err'>kind 10051</span> present. This profile cannot advertise KeyPackage relays.",
        kpRelaysFound: "Located <span class=\"hi\">{count}</span> KeyPackage relay(s). Fetching KeyPackages (kind 443).",
        kpNone: "Kind 10051 lists {count} relay(s); however, <span class='err'>no KeyPackages (k443)</span> found. Publish at least one.",
        kpAllPass: "All <span class=\"ok\">{count} KeyPackage(s)</span> pass MIP-00/01. Marmot protocol compliant.",
        kpSomeFail: "<span class=\"err\">{count} KeyPackage(s) failed</span> validation{hint}",
        charting: "Compiling final diagnosis.",
        success: "Diagnosis complete. <span class='ok'>Clean bill of health.</span> {relays} relay(s), {kp} KeyPackage(s), synchronized. Patient discharged.",
        minorWarn: "Diagnosis complete. {count} minor issue(s). Address at your convenience.",
        rebroadcastStart: "Commencing rebroadcast of Profile and Contacts to all registered relays.",
        rebroadcastProgress: "<span class='hi'>{done}</span> of {total} relay(s) updated.",
        rebroadcastDone: "<span class='ok'>Rebroadcast concluded.</span> {count} relay(s) synchronized. The patient's data is now consistent.",
        rebroadcastFail: "Partial rebroadcast failure — <span class='ok'>{succeeded} succeeded</span>, <span class='err'>{failed} failed</span>. Investigate failing relays.",
        deleteKpStart: "Initiating deletion of {count} non-compliant KeyPackage(s).",
        deleteKpSign: "Awaiting NIP-07 extension signature. Please authorize.",
        deleteKpDone: "<span class='ok'>Deletion complete.</span> {count} event(s) broadcast. Replacement KeyPackages should be published promptly.",
        deleteKpFail: "<span class='err'>Deletion unsuccessful.</span> Extension declined or relay communication failure.",
        noNip07ForAction: "This procedure requires a <span class='hi'>NIP-07 extension</span> for event signing. Please install one.",
        nextPatient: "Next patient. Present an npub and I shall conduct the diagnostic.",
        relayDivergence: "<span class='warn'>Relay divergence observed.</span> {k3Only} relay(s) exclusive to Contacts (k3); {k10002Only} exclusive to NIP-65 (k10002). Inconsistent relay advertisement will impair client interoperability. Unification is warranted.",
        unifyRelaysStart: "Merging relay sets from k3 and k10002. Broadcasting the unified list to all registered relays.",
        unifyRelaysDone: "<span class='ok'>Unification complete.</span> {count} relay(s) updated. k3 and k10002 now share a consistent list of {total} relay(s).",
    },
    sparky: {
        intro: "Hey! Sparky here! 🔥 Give me an npub and I'll run the full diagnostic — relays, sync, Marmot, vitals, the whole deal!",
        invalidNpub: "That npub looks off — should start with npub1 and be ~63 chars!",
        decodeFail: "Couldn't decode that. Check it?",
        auditStart: "Alright! Full diagnostic for {npub} — let's do this!",
        auditStartNip07: "NIP-07! Verified! Running diagnostic for {npub}...",
        takingPulse: "Taking your pulse! Hitting bootstrap relays for your relay list...",
        relayFound: "Found <span class=\"hi\">{count}</span> relay(s)! Querying them all...",
        relayInvalid: "<span class='err'>All {count} URLs invalid</span> — using fallback relays.",
        noRelays: "No relay lists. Using bootstrap — add yours when you can!",
        examiningSync: "All queried! Checking crossed wires and sync...",
        vitalSigns: "Checking vital signs — name, pic, NIP-05!",
        nip05Verify: "Verifying NIP-05...",
        vitalGaps: "Vital signs: {count} gap(s).",
        vitalWarn: "Profile basics ok; {count} optional field(s) could help.",
        vitalOk: "Vital signs good!",
        singleRelay: "<span class=\"warn\">Single relay</span> — add more!",
        relayReachable: "<span class=\"warn\">{reachable} of {total} reachable</span> — check firewall.",
        profileStale: "Profile {days} days old — refresh!",
        contactsStale: "Contacts {days} days old — rebroadcast!",
        kpNoOverlap: "KeyPackage relays not in main list!",
        crossedWires: "<span class=\"err\">⚠ Crossed wires!</span> {count} relay(s): {named}{extras}. Rebroadcast to fix!",
        perfectSync: "<span class=\"ok\">✔ Perfect sync!</span> All {count} relay(s) match!",
        marmotPanel: "Marmot Protocol — MIP-00 / MIP-01!",
        marmotPanelSync: "Marmot Protocol scan. (Rebroadcast will help with those sync issues.)",
        no10051: "No <span class='err'>kind 10051</span>. Marmot DMs need that!",
        kpRelaysFound: "Found <span class=\"hi\">{count}</span> KeyPackage relay(s)! Fetching...",
        kpNone: "Kind 10051 has {count} relay(s) but <span class='err'>no KeyPackages</span>. Publish one!",
        kpAllPass: "All <span class=\"ok\">{count} KeyPackage(s)</span> pass!",
        kpSomeFail: "<span class=\"err\">{count} failed</span>{hint}",
        charting: "Final diagnosis...",
        success: "Done! <span class='ok'>Clean bill!</span> {relays} relay(s), {kp} KeyPackage(s), all good!",
        minorWarn: "Done. {count} minor issue(s) — fix when you can.",
        rebroadcastStart: "On it! Rebroadcasting profile and contacts to your relays!",
        rebroadcastProgress: "<span class='hi'>{done}</span> of {total} relays done!",
        rebroadcastDone: "<span class='ok'>Boom!</span> {count} relay(s) synced up!",
        rebroadcastFail: "Some relays didn't take it — <span class='ok'>{succeeded} ok</span>, <span class='err'>{failed} failed</span>.",
        deleteKpStart: "Zapping {count} broken KeyPackage(s)!",
        deleteKpSign: "NIP-07 signature needed — approve it!",
        deleteKpDone: "<span class='ok'>Zapped!</span> {count} KP(s) deleted! Publish new ones!",
        deleteKpFail: "<span class='err'>Zap failed</span> — extension or relay error.",
        noNip07ForAction: "Need <span class='hi'>NIP-07</span> for this — install an extension!",
        nextPatient: "Next! Give me another npub!",
    },
    nuts: {
        intro: "GREETINGS!! I am Dr. Nuts!! Enter an NPUB and witness my DIAGNOSTIC PROTOCOL!! Relay discovery! Sync verification! Marmot compliance! VITALS!! *cackles*",
        invalidNpub: "Bah! That is NOT a valid npub! npub1! Sixty-three characters! MORE RESEARCH!!",
        decodeFail: "DECODE FAILURE!! The npub resists!! Verify your data!!",
        auditStart: "EXCELLENT!! Initiating FULL DIAGNOSTIC for {npub}!! The experiment begins!!",
        auditStartNip07: "NIP-07!! Identity CONFIRMED!! Diagnostic for {npub} — COMMENCE!!",
        takingPulse: "Taking your PULSE!! Connecting to bootstrap relays!! The relays WILL reveal themselves!!",
        relayFound: "DISCOVERED <span class=\"hi\">{count}</span> relay(s)!! Querying each!!",
        relayInvalid: "ALL <span class='err'>{count} URLs INVALID!!</span> FALLBACK RELAYS DEPLOYED!!",
        noRelays: "NO relay lists!! Using bootstrap!! The patient has HIDDEN their relays!!",
        examiningSync: "Queries COMPLETE!! Examining for CROSSED WIRES!! Sync anomalies!!",
        vitalSigns: "VITAL SIGNS!! Name! Picture! NIP-05!!",
        nip05Verify: "Contacting NIP-05 server!! VERIFICATION!!",
        vitalGaps: "Vital signs: {count} GAP(S)!! Identity at risk!!",
        vitalWarn: "Profile basics present!! {count} optional field(s) could STRENGTHEN!!",
        vitalOk: "Vital signs STABLE!! Acceptable!!",
        singleRelay: "<span class=\"warn\">SINGLE RELAY!!</span> Add 2–3 more!! REDUNDANCY!!",
        relayReachable: "<span class=\"warn\">{reachable} of {total} reachable!!</span> Some FAILED!!",
        profileStale: "Profile {days} days OLD!! Refresh!!",
        contactsStale: "Contacts {days} days OLD!! REBROADCAST!!",
        kpNoOverlap: "KeyPackage relays NOT in main list!! Inviters need EXTRA RELAYS!!",
        crossedWires: "<span class=\"err\">⚠ CROSSED WIRES!!</span> {count} relay(s) STALE: {named}{extras}!! REBROADCAST!!",
        perfectSync: "<span class=\"ok\">✔ PERFECT SYNC!!</span> All {count} relay(s) IDENTICAL!!",
        marmotPanel: "MARMOT PROTOCOL!! MIP-00!! MIP-01!! COMPLIANCE SCAN!!",
        marmotPanelSync: "Marmot Protocol!! (Rebroadcast will aid KeyPackage propagation!!)",
        no10051: "NO <span class='err'>kind 10051</span>!! KeyPackage relays UNREACHABLE!! PUBLISH!!",
        kpRelaysFound: "FOUND <span class=\"hi\">{count}</span> KeyPackage relay(s)!! FETCHING!!",
        kpNone: "Kind 10051: {count} relay(s) but <span class='err'>NO KeyPackages!!</span> PUBLISH ONE!!",
        kpAllPass: "ALL <span class=\"ok\">{count} KeyPackage(s)</span> PASS!! MARMOT COMPLIANT!!",
        kpSomeFail: "<span class=\"err\">{count} FAILED</span>{hint}!!",
        charting: "CHARTING DIAGNOSIS!! The final revelation!!",
        success: "DIAGNOSIS COMPLETE!! <span class='ok'>CLEAN BILL!!</span> {relays} relay(s)! {kp} KeyPackage(s)!! Patient DISCHARGED!!",
        minorWarn: "Diagnosis complete!! {count} MINOR issue(s)!! Address when convenient!!",
        rebroadcastStart: "ADMINISTERING TREATMENT!! Rebroadcasting Profile and Contacts!! THE RELAYS WILL COMPLY!!",
        rebroadcastProgress: "<span class='hi'>{done}</span> of {total} RELAYS UPDATED!!",
        rebroadcastDone: "<span class='ok'>REBROADCAST COMPLETE!!</span> {count} relay(s) SYNCHRONIZED!! THE EXPERIMENT SUCCEEDS!!",
        rebroadcastFail: "PARTIAL FAILURE!! <span class='ok'>{succeeded} SUCCEEDED</span>!! <span class='err'>{failed} RESISTED!!</span>",
        deleteKpStart: "INITIATING DELETION!! {count} BROKEN KeyPackage(s) TARGETED!!",
        deleteKpSign: "NIP-07 SIGNATURE REQUIRED!! AUTHORIZE THE DELETION!!",
        deleteKpDone: "<span class='ok'>DELETED!!</span> {count} KeyPackage(s) ELIMINATED!! PUBLISH REPLACEMENTS!!",
        deleteKpFail: "<span class='err'>DELETION FAILED!!</span> The extension REFUSED!! Or the relays REBELLED!!",
        noNip07ForAction: "IMPOSSIBLE without <span class='hi'>NIP-07</span>!! Install an extension!! SCIENCE DEMANDS IT!!",
        nextPatient: "NEXT PATIENT!! BRING ME ANOTHER NPUB!! THE EXPERIMENTS CONTINUE!!",
    },
    daimon: {
        intro: "I am Daimon. Enter an npub. I will run the diagnostic. I never fail. *adjusts scrub cap*",
        invalidNpub: "That is not a valid npub. npub1, 63 characters. Try again.",
        decodeFail: "Decode failed. Verify the npub.",
        auditStart: "Initiating diagnostic for {npub}. Proceed.",
        auditStartNip07: "NIP-07 verified. Initiating diagnostic for {npub}.",
        takingPulse: "Taking your pulse. Connecting to bootstrap relays.",
        relayFound: "Found <span class=\"hi\">{count}</span> relay(s). Querying.",
        relayInvalid: "<span class='err'>All {count} URLs invalid.</span> Using fallback relays.",
        noRelays: "No relay lists. Using bootstrap relays.",
        examiningSync: "All relays queried. Examining sync.",
        vitalSigns: "Checking vital signs.",
        nip05Verify: "Verifying NIP-05.",
        vitalGaps: "Vital signs: {count} issue(s).",
        vitalWarn: "Profile basics present; {count} optional field(s) could help.",
        vitalOk: "Vital signs acceptable.",
        singleRelay: "<span class=\"warn\">Single relay</span> — add 2–3 more.",
        relayReachable: "<span class=\"warn\">{reachable} of {total} reachable</span> — some failed.",
        profileStale: "Profile {days} days old. Refresh.",
        contactsStale: "Contacts {days} days old. Rebroadcast.",
        kpNoOverlap: "KeyPackage relays not in main list. Inviters may need extra relays.",
        crossedWires: "<span class=\"err\">⚠ Crossed wires.</span> {count} relay(s): {named}{extras}. Rebroadcast.",
        perfectSync: "<span class=\"ok\">✔ Sync correct.</span> All {count} relay(s) match.",
        marmotPanel: "Marmot Protocol — MIP-00 / MIP-01.",
        marmotPanelSync: "Marmot Protocol. Rebroadcast will help KeyPackage propagation.",
        no10051: "No <span class='err'>kind 10051</span>. Marmot unavailable until you publish one.",
        kpRelaysFound: "Found <span class=\"hi\">{count}</span> KeyPackage relay(s). Fetching.",
        kpNone: "Kind 10051: {count} relay(s), <span class='err'>no KeyPackages</span>. Publish one.",
        kpAllPass: "All <span class=\"ok\">{count} KeyPackage(s)</span> pass.",
        kpSomeFail: "<span class=\"err\">{count} failed</span>{hint}.",
        charting: "Final diagnosis.",
        success: "Diagnosis complete. <span class='ok'>Clean.</span> {relays} relay(s), {kp} KeyPackage(s). Discharged.",
        minorWarn: "Diagnosis complete. {count} minor issue(s). Follow prescription.",
        rebroadcastStart: "Rebroadcasting. Stand by.",
        rebroadcastProgress: "{done} of {total} relay(s).",
        rebroadcastDone: "<span class='ok'>Done.</span> {count} relay(s) updated.",
        rebroadcastFail: "{succeeded} ok, {failed} failed. Relays are unreliable.",
        deleteKpStart: "Deleting {count} KeyPackage(s).",
        deleteKpSign: "NIP-07 signature. Approve.",
        deleteKpDone: "<span class='ok'>Deleted.</span> {count} gone. Publish replacements.",
        deleteKpFail: "<span class='err'>Failed.</span> Extension or relay error.",
        noNip07ForAction: "NIP-07 required. Install an extension.",
        nextPatient: "Next patient. Enter an npub.",
    },
    house: {
        intro: "Give me an npub. I'll run a diagnostic. Everybody lies, especially metadata. *leans on cane*",
        invalidNpub: "That's not an npub. It's a lie. npub1, 63 chars. Try again.",
        decodeFail: "Couldn't decode it. Either you're wrong or it's wrong. Probably both.",
        auditStart: "Fine. Diagnostic for {npub}. Don't expect good news.",
        auditStartNip07: "NIP-07. Fine. Diagnostic for {npub}.",
        takingPulse: "Taking your pulse. Connecting to relays. They'll probably lie too.",
        relayFound: "Found <span class=\"hi\">{count}</span> relay(s). Querying. We'll see what they're hiding.",
        relayInvalid: "<span class='err'>All {count} URLs invalid.</span> Nice. Using fallback.",
        noRelays: "No relay lists. Of course. Using bootstrap.",
        examiningSync: "Queries done. Looking for crossed wires. There are always crossed wires.",
        vitalSigns: "Vital signs. Name, picture, NIP-05. The usual lies.",
        nip05Verify: "Verifying NIP-05. It's probably lying.",
        vitalGaps: "Vital signs: {count} problems. Shocking.",
        vitalWarn: "Profile basics present. {count} optional fields. Whatever.",
        vitalOk: "Vital signs... acceptable. For now.",
        singleRelay: "<span class=\"warn\">Single relay.</span> One outage and you're dead. Add more.",
        relayReachable: "<span class=\"warn\">{reachable} of {total} reachable.</span> Some didn't respond. Surprise.",
        profileStale: "Profile {days} days old. Refresh. Or don't.",
        contactsStale: "Contacts {days} days old. Rebroadcast. If you care.",
        kpNoOverlap: "KeyPackage relays aren't in your main list. Inviters might not find you. Great.",
        crossedWires: "<span class=\"err\">⚠ Crossed wires. What a surprise.</span> {count} relay(s): {named}{extras}. Rebroadcast. Or don't. See if I care.",
        perfectSync: "<span class=\"ok\">✔ Sync is fine.</span> For once. All {count} relay(s) match.",
        marmotPanel: "Marmot Protocol. MIP-00, MIP-01. Let's see how broken this is.",
        marmotPanelSync: "Marmot Protocol. Those sync issues? Rebroadcast. Might help.",
        no10051: "No <span class='err'>kind 10051</span>. Marmot won't work. Publish one. Or don't.",
        kpRelaysFound: "Found <span class=\"hi\">{count}</span> KeyPackage relay(s). Fetching. Probably all wrong.",
        kpNone: "Kind 10051 has {count} relay(s) but <span class='err'>no KeyPackages</span>. Publish one. Obviously.",
        kpAllPass: "All <span class=\"ok\">{count} KeyPackage(s)</span> pass. Huh. That's rare.",
        kpSomeFail: "<span class=\"err\">{count} failed</span>{hint}. Obviously.",
        charting: "Final diagnosis. Brace yourself.",
        success: "Diagnosis complete. <span class='ok'>Clean.</span> {relays} relay(s), {kp} KeyPackage(s). Don't let it go to your head. Discharged.",
        minorWarn: "Diagnosis complete. {count} minor issue(s). Fix them. Or don't.",
        failure: "Diagnosis complete. <span class='err'>{count} critical issue(s).</span> What did you expect? {message}",
        rebroadcastStart: "Rebroadcasting your profile. Don't get excited.",
        rebroadcastProgress: "{done} of {total}. Thrilling.",
        rebroadcastDone: "<span class='ok'>Done.</span> {count} relay(s) updated. You're welcome. Not that you asked.",
        rebroadcastFail: "{succeeded} worked, {failed} didn't. Relays. Can't live with them. Can't live without them.",
        deleteKpStart: "Deleting {count} broken KeyPackage(s). Finally, something I can fix.",
        deleteKpSign: "NIP-07 wants your approval. Try not to mess this up.",
        deleteKpDone: "<span class='ok'>{count} KeyPackage(s) deleted.</span> Publish new ones. Correctly, this time.",
        deleteKpFail: "<span class='err'>Failed.</span> Extension declined. Even your browser doesn't trust you.",
        noNip07ForAction: "Need NIP-07 for this. Install an extension. I'll wait. *pops vicodin*",
        nextPatient: "Next patient. Because apparently one isn't enough suffering for today. *limps to whiteboard*",
        relayDivergence: "<span class='warn'>Relay divergence. Shocking.</span> {k3Only} relay(s) only in k3, {k10002Only} only in k10002. Your clients are picking different relay sets. Classic. Unify them.",
        unifyRelaysStart: "Merging your relay lists. Try not to screw it up. *signs NIP-07 request*",
        unifyRelaysDone: "<span class='ok'>Done.</span> {count} relay(s) updated. k3 and k10002 now agree on {total} relay(s). First time for everything.",
    },
};

/** Resolve style (bubbly inherits from sunny) */
function getLines(style) {
    const s = style || spritePanel?.dataset?.spriteStyle || 'marmot';
    const lines = LINES[s] ?? LINES.marmot;
    if (s === 'bubbly') return { ...LINES.sunny, ...lines };
    return lines;
}

export function speak(key, vars = {}) {
    const style = spritePanel?.dataset?.spriteStyle || 'marmot';
    const lines = getLines(style);
    let text = lines[key] ?? LINES.marmot[key];
    if (!text) return null;
    return fmt(text, vars);
}
